//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetLongitud
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionResult", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    public partial class ConversionResult : object
    {
        
        private DotNetLongitud.ConversionError ErrorField;
        
        private bool ExitosoField;
        
        private DotNetLongitud.UnidadConversion ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DotNetLongitud.ConversionError Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso
        {
            get
            {
                return this.ExitosoField;
            }
            set
            {
                this.ExitosoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DotNetLongitud.UnidadConversion Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionError", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    public partial class ConversionError : object
    {
        
        private string CodigoErrorField;
        
        private string DetallesField;
        
        private System.DateTime FechaErrorField;
        
        private string MensajeField;
        
        private string TipoErrorField;
        
        private string UnidadField;
        
        private System.Nullable<double> ValorProblematicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoError
        {
            get
            {
                return this.CodigoErrorField;
            }
            set
            {
                this.CodigoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalles
        {
            get
            {
                return this.DetallesField;
            }
            set
            {
                this.DetallesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaError
        {
            get
            {
                return this.FechaErrorField;
            }
            set
            {
                this.FechaErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoError
        {
            get
            {
                return this.TipoErrorField;
            }
            set
            {
                this.TipoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidad
        {
            get
            {
                return this.UnidadField;
            }
            set
            {
                this.UnidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValorProblematico
        {
            get
            {
                return this.ValorProblematicoField;
            }
            set
            {
                this.ValorProblematicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadConversion", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    public partial class UnidadConversion : object
    {
        
        private double FactorConversionField;
        
        private System.DateTime FechaConversionField;
        
        private string UnidadDestinoField;
        
        private string UnidadOrigenField;
        
        private double ValorConvertidoExactoField;
        
        private double ValorConvertidoRedondeadoField;
        
        private double ValorOriginalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FactorConversion
        {
            get
            {
                return this.FactorConversionField;
            }
            set
            {
                this.FactorConversionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaConversion
        {
            get
            {
                return this.FechaConversionField;
            }
            set
            {
                this.FechaConversionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadDestino
        {
            get
            {
                return this.UnidadDestinoField;
            }
            set
            {
                this.UnidadDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadOrigen
        {
            get
            {
                return this.UnidadOrigenField;
            }
            set
            {
                this.UnidadOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertidoExacto
        {
            get
            {
                return this.ValorConvertidoExactoField;
            }
            set
            {
                this.ValorConvertidoExactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertidoRedondeado
        {
            get
            {
                return this.ValorConvertidoRedondeadoField;
            }
            set
            {
                this.ValorConvertidoRedondeadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorOriginal
        {
            get
            {
                return this.ValorOriginalField;
            }
            set
            {
                this.ValorOriginalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DotNetLongitud.ILongitudService")]
    public interface ILongitudService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/MillaAMetro", ReplyAction="http://tempuri.org/ILongitudService/MillaAMetroResponse")]
        System.Threading.Tasks.Task<DotNetLongitud.ConversionResult> MillaAMetroAsync(string millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/MetroAMilla", ReplyAction="http://tempuri.org/ILongitudService/MetroAMillaResponse")]
        System.Threading.Tasks.Task<DotNetLongitud.ConversionResult> MetroAMillaAsync(string metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/MillaAPulgada", ReplyAction="http://tempuri.org/ILongitudService/MillaAPulgadaResponse")]
        System.Threading.Tasks.Task<DotNetLongitud.ConversionResult> MillaAPulgadaAsync(string millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/PulgadaAMilla", ReplyAction="http://tempuri.org/ILongitudService/PulgadaAMillaResponse")]
        System.Threading.Tasks.Task<DotNetLongitud.ConversionResult> PulgadaAMillaAsync(string pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/MetroAPulgada", ReplyAction="http://tempuri.org/ILongitudService/MetroAPulgadaResponse")]
        System.Threading.Tasks.Task<DotNetLongitud.ConversionResult> MetroAPulgadaAsync(string metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/PulgadaAMetro", ReplyAction="http://tempuri.org/ILongitudService/PulgadaAMetroResponse")]
        System.Threading.Tasks.Task<DotNetLongitud.ConversionResult> PulgadaAMetroAsync(string pulgadas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ILongitudServiceChannel : DotNetLongitud.ILongitudService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class LongitudServiceClient : System.ServiceModel.ClientBase<DotNetLongitud.ILongitudService>, DotNetLongitud.ILongitudService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LongitudServiceClient() : 
                base(LongitudServiceClient.GetDefaultBinding(), LongitudServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ILongitudService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LongitudServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LongitudServiceClient.GetBindingForEndpoint(endpointConfiguration), LongitudServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LongitudServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LongitudServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LongitudServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LongitudServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LongitudServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<DotNetLongitud.ConversionResult> MillaAMetroAsync(string millas)
        {
            return base.Channel.MillaAMetroAsync(millas);
        }
        
        public System.Threading.Tasks.Task<DotNetLongitud.ConversionResult> MetroAMillaAsync(string metros)
        {
            return base.Channel.MetroAMillaAsync(metros);
        }
        
        public System.Threading.Tasks.Task<DotNetLongitud.ConversionResult> MillaAPulgadaAsync(string millas)
        {
            return base.Channel.MillaAPulgadaAsync(millas);
        }
        
        public System.Threading.Tasks.Task<DotNetLongitud.ConversionResult> PulgadaAMillaAsync(string pulgadas)
        {
            return base.Channel.PulgadaAMillaAsync(pulgadas);
        }
        
        public System.Threading.Tasks.Task<DotNetLongitud.ConversionResult> MetroAPulgadaAsync(string metros)
        {
            return base.Channel.MetroAPulgadaAsync(metros);
        }
        
        public System.Threading.Tasks.Task<DotNetLongitud.ConversionResult> PulgadaAMetroAsync(string pulgadas)
        {
            return base.Channel.PulgadaAMetroAsync(pulgadas);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILongitudService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILongitudService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56686/ec/edu/monster/ws/LongitudService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LongitudServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ILongitudService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LongitudServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ILongitudService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ILongitudService,
        }
    }
}
