//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebConversion.MasaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionResult", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    [System.SerializableAttribute()]
    public partial class ConversionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWebConversion.MasaServiceReference.ConversionError ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitosoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWebConversion.MasaServiceReference.UnidadConversion ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWebConversion.MasaServiceReference.ConversionError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso {
            get {
                return this.ExitosoField;
            }
            set {
                if ((this.ExitosoField.Equals(value) != true)) {
                    this.ExitosoField = value;
                    this.RaisePropertyChanged("Exitoso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWebConversion.MasaServiceReference.UnidadConversion Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionError", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    [System.SerializableAttribute()]
    public partial class ConversionError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetallesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ValorProblematicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoErrorField, value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalles {
            get {
                return this.DetallesField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesField, value) != true)) {
                    this.DetallesField = value;
                    this.RaisePropertyChanged("Detalles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaError {
            get {
                return this.FechaErrorField;
            }
            set {
                if ((this.FechaErrorField.Equals(value) != true)) {
                    this.FechaErrorField = value;
                    this.RaisePropertyChanged("FechaError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoError {
            get {
                return this.TipoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoErrorField, value) != true)) {
                    this.TipoErrorField = value;
                    this.RaisePropertyChanged("TipoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidad {
            get {
                return this.UnidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadField, value) != true)) {
                    this.UnidadField = value;
                    this.RaisePropertyChanged("Unidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValorProblematico {
            get {
                return this.ValorProblematicoField;
            }
            set {
                if ((this.ValorProblematicoField.Equals(value) != true)) {
                    this.ValorProblematicoField = value;
                    this.RaisePropertyChanged("ValorProblematico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadConversion", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    [System.SerializableAttribute()]
    public partial class UnidadConversion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FactorConversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaConversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorConvertidoExactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorConvertidoRedondeadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorOriginalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FactorConversion {
            get {
                return this.FactorConversionField;
            }
            set {
                if ((this.FactorConversionField.Equals(value) != true)) {
                    this.FactorConversionField = value;
                    this.RaisePropertyChanged("FactorConversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaConversion {
            get {
                return this.FechaConversionField;
            }
            set {
                if ((this.FechaConversionField.Equals(value) != true)) {
                    this.FechaConversionField = value;
                    this.RaisePropertyChanged("FechaConversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadDestino {
            get {
                return this.UnidadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadDestinoField, value) != true)) {
                    this.UnidadDestinoField = value;
                    this.RaisePropertyChanged("UnidadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadOrigen {
            get {
                return this.UnidadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadOrigenField, value) != true)) {
                    this.UnidadOrigenField = value;
                    this.RaisePropertyChanged("UnidadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertidoExacto {
            get {
                return this.ValorConvertidoExactoField;
            }
            set {
                if ((this.ValorConvertidoExactoField.Equals(value) != true)) {
                    this.ValorConvertidoExactoField = value;
                    this.RaisePropertyChanged("ValorConvertidoExacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertidoRedondeado {
            get {
                return this.ValorConvertidoRedondeadoField;
            }
            set {
                if ((this.ValorConvertidoRedondeadoField.Equals(value) != true)) {
                    this.ValorConvertidoRedondeadoField = value;
                    this.RaisePropertyChanged("ValorConvertidoRedondeado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorOriginal {
            get {
                return this.ValorOriginalField;
            }
            set {
                if ((this.ValorOriginalField.Equals(value) != true)) {
                    this.ValorOriginalField = value;
                    this.RaisePropertyChanged("ValorOriginal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MasaServiceReference.IMasaService")]
    public interface IMasaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/KilogramoAQuintal", ReplyAction="http://tempuri.org/IMasaService/KilogramoAQuintalResponse")]
        ClienteWebConversion.MasaServiceReference.ConversionResult KilogramoAQuintal(string kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/KilogramoAQuintal", ReplyAction="http://tempuri.org/IMasaService/KilogramoAQuintalResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.MasaServiceReference.ConversionResult> KilogramoAQuintalAsync(string kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/QuintalAKilogramo", ReplyAction="http://tempuri.org/IMasaService/QuintalAKilogramoResponse")]
        ClienteWebConversion.MasaServiceReference.ConversionResult QuintalAKilogramo(string quintales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/QuintalAKilogramo", ReplyAction="http://tempuri.org/IMasaService/QuintalAKilogramoResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.MasaServiceReference.ConversionResult> QuintalAKilogramoAsync(string quintales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/KilogramoALibra", ReplyAction="http://tempuri.org/IMasaService/KilogramoALibraResponse")]
        ClienteWebConversion.MasaServiceReference.ConversionResult KilogramoALibra(string kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/KilogramoALibra", ReplyAction="http://tempuri.org/IMasaService/KilogramoALibraResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.MasaServiceReference.ConversionResult> KilogramoALibraAsync(string kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/LibraAKilogramo", ReplyAction="http://tempuri.org/IMasaService/LibraAKilogramoResponse")]
        ClienteWebConversion.MasaServiceReference.ConversionResult LibraAKilogramo(string libras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/LibraAKilogramo", ReplyAction="http://tempuri.org/IMasaService/LibraAKilogramoResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.MasaServiceReference.ConversionResult> LibraAKilogramoAsync(string libras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/QuintalALibra", ReplyAction="http://tempuri.org/IMasaService/QuintalALibraResponse")]
        ClienteWebConversion.MasaServiceReference.ConversionResult QuintalALibra(string quintales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/QuintalALibra", ReplyAction="http://tempuri.org/IMasaService/QuintalALibraResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.MasaServiceReference.ConversionResult> QuintalALibraAsync(string quintales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/LibraAQuintal", ReplyAction="http://tempuri.org/IMasaService/LibraAQuintalResponse")]
        ClienteWebConversion.MasaServiceReference.ConversionResult LibraAQuintal(string libras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/LibraAQuintal", ReplyAction="http://tempuri.org/IMasaService/LibraAQuintalResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.MasaServiceReference.ConversionResult> LibraAQuintalAsync(string libras);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMasaServiceChannel : ClienteWebConversion.MasaServiceReference.IMasaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MasaServiceClient : System.ServiceModel.ClientBase<ClienteWebConversion.MasaServiceReference.IMasaService>, ClienteWebConversion.MasaServiceReference.IMasaService {
        
        public MasaServiceClient() {
        }
        
        public MasaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MasaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteWebConversion.MasaServiceReference.ConversionResult KilogramoAQuintal(string kilogramos) {
            return base.Channel.KilogramoAQuintal(kilogramos);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.MasaServiceReference.ConversionResult> KilogramoAQuintalAsync(string kilogramos) {
            return base.Channel.KilogramoAQuintalAsync(kilogramos);
        }
        
        public ClienteWebConversion.MasaServiceReference.ConversionResult QuintalAKilogramo(string quintales) {
            return base.Channel.QuintalAKilogramo(quintales);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.MasaServiceReference.ConversionResult> QuintalAKilogramoAsync(string quintales) {
            return base.Channel.QuintalAKilogramoAsync(quintales);
        }
        
        public ClienteWebConversion.MasaServiceReference.ConversionResult KilogramoALibra(string kilogramos) {
            return base.Channel.KilogramoALibra(kilogramos);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.MasaServiceReference.ConversionResult> KilogramoALibraAsync(string kilogramos) {
            return base.Channel.KilogramoALibraAsync(kilogramos);
        }
        
        public ClienteWebConversion.MasaServiceReference.ConversionResult LibraAKilogramo(string libras) {
            return base.Channel.LibraAKilogramo(libras);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.MasaServiceReference.ConversionResult> LibraAKilogramoAsync(string libras) {
            return base.Channel.LibraAKilogramoAsync(libras);
        }
        
        public ClienteWebConversion.MasaServiceReference.ConversionResult QuintalALibra(string quintales) {
            return base.Channel.QuintalALibra(quintales);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.MasaServiceReference.ConversionResult> QuintalALibraAsync(string quintales) {
            return base.Channel.QuintalALibraAsync(quintales);
        }
        
        public ClienteWebConversion.MasaServiceReference.ConversionResult LibraAQuintal(string libras) {
            return base.Channel.LibraAQuintal(libras);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.MasaServiceReference.ConversionResult> LibraAQuintalAsync(string libras) {
            return base.Channel.LibraAQuintalAsync(libras);
        }
    }
}
