//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConUni_CliEsc_GR01.MasaServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionResult", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    public partial class ConversionResult : object
    {
        
        private ConUni_CliEsc_GR01.MasaServiceReference.ConversionError ErrorField;
        
        private bool ExitosoField;
        
        private ConUni_CliEsc_GR01.MasaServiceReference.UnidadConversion ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConUni_CliEsc_GR01.MasaServiceReference.ConversionError Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso
        {
            get
            {
                return this.ExitosoField;
            }
            set
            {
                this.ExitosoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConUni_CliEsc_GR01.MasaServiceReference.UnidadConversion Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionError", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    public partial class ConversionError : object
    {
        
        private string CodigoErrorField;
        
        private string DetallesField;
        
        private System.DateTime FechaErrorField;
        
        private string MensajeField;
        
        private string TipoErrorField;
        
        private string UnidadField;
        
        private System.Nullable<double> ValorProblematicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoError
        {
            get
            {
                return this.CodigoErrorField;
            }
            set
            {
                this.CodigoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalles
        {
            get
            {
                return this.DetallesField;
            }
            set
            {
                this.DetallesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaError
        {
            get
            {
                return this.FechaErrorField;
            }
            set
            {
                this.FechaErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoError
        {
            get
            {
                return this.TipoErrorField;
            }
            set
            {
                this.TipoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidad
        {
            get
            {
                return this.UnidadField;
            }
            set
            {
                this.UnidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValorProblematico
        {
            get
            {
                return this.ValorProblematicoField;
            }
            set
            {
                this.ValorProblematicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadConversion", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    public partial class UnidadConversion : object
    {
        
        private double FactorConversionField;
        
        private System.DateTime FechaConversionField;
        
        private string UnidadDestinoField;
        
        private string UnidadOrigenField;
        
        private double ValorConvertidoExactoField;
        
        private double ValorConvertidoRedondeadoField;
        
        private double ValorOriginalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FactorConversion
        {
            get
            {
                return this.FactorConversionField;
            }
            set
            {
                this.FactorConversionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaConversion
        {
            get
            {
                return this.FechaConversionField;
            }
            set
            {
                this.FechaConversionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadDestino
        {
            get
            {
                return this.UnidadDestinoField;
            }
            set
            {
                this.UnidadDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadOrigen
        {
            get
            {
                return this.UnidadOrigenField;
            }
            set
            {
                this.UnidadOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertidoExacto
        {
            get
            {
                return this.ValorConvertidoExactoField;
            }
            set
            {
                this.ValorConvertidoExactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertidoRedondeado
        {
            get
            {
                return this.ValorConvertidoRedondeadoField;
            }
            set
            {
                this.ValorConvertidoRedondeadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorOriginal
        {
            get
            {
                return this.ValorOriginalField;
            }
            set
            {
                this.ValorOriginalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConUni_CliEsc_GR01.MasaServiceReference.IMasaService")]
    public interface IMasaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/KilogramoAQuintal", ReplyAction="http://tempuri.org/IMasaService/KilogramoAQuintalResponse")]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.MasaServiceReference.ConversionResult> KilogramoAQuintalAsync(string kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/QuintalAKilogramo", ReplyAction="http://tempuri.org/IMasaService/QuintalAKilogramoResponse")]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.MasaServiceReference.ConversionResult> QuintalAKilogramoAsync(string quintales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/KilogramoALibra", ReplyAction="http://tempuri.org/IMasaService/KilogramoALibraResponse")]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.MasaServiceReference.ConversionResult> KilogramoALibraAsync(string kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/LibraAKilogramo", ReplyAction="http://tempuri.org/IMasaService/LibraAKilogramoResponse")]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.MasaServiceReference.ConversionResult> LibraAKilogramoAsync(string libras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/QuintalALibra", ReplyAction="http://tempuri.org/IMasaService/QuintalALibraResponse")]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.MasaServiceReference.ConversionResult> QuintalALibraAsync(string quintales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasaService/LibraAQuintal", ReplyAction="http://tempuri.org/IMasaService/LibraAQuintalResponse")]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.MasaServiceReference.ConversionResult> LibraAQuintalAsync(string libras);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IMasaServiceChannel : ConUni_CliEsc_GR01.MasaServiceReference.IMasaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class MasaServiceClient : System.ServiceModel.ClientBase<ConUni_CliEsc_GR01.MasaServiceReference.IMasaService>, ConUni_CliEsc_GR01.MasaServiceReference.IMasaService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MasaServiceClient() : 
                base(MasaServiceClient.GetDefaultBinding(), MasaServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMasaService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MasaServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MasaServiceClient.GetBindingForEndpoint(endpointConfiguration), MasaServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MasaServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MasaServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MasaServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MasaServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MasaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.MasaServiceReference.ConversionResult> KilogramoAQuintalAsync(string kilogramos)
        {
            return base.Channel.KilogramoAQuintalAsync(kilogramos);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.MasaServiceReference.ConversionResult> QuintalAKilogramoAsync(string quintales)
        {
            return base.Channel.QuintalAKilogramoAsync(quintales);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.MasaServiceReference.ConversionResult> KilogramoALibraAsync(string kilogramos)
        {
            return base.Channel.KilogramoALibraAsync(kilogramos);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.MasaServiceReference.ConversionResult> LibraAKilogramoAsync(string libras)
        {
            return base.Channel.LibraAKilogramoAsync(libras);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.MasaServiceReference.ConversionResult> QuintalALibraAsync(string quintales)
        {
            return base.Channel.QuintalALibraAsync(quintales);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.MasaServiceReference.ConversionResult> LibraAQuintalAsync(string libras)
        {
            return base.Channel.LibraAQuintalAsync(libras);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMasaService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMasaService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56686/ec/edu/monster/ws/MasaService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MasaServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMasaService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MasaServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMasaService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMasaService,
        }
    }
}
