//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebConversion.TemperaturaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionResult", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    [System.SerializableAttribute()]
    public partial class ConversionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWebConversion.TemperaturaServiceReference.ConversionError ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitosoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWebConversion.TemperaturaServiceReference.UnidadConversion ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWebConversion.TemperaturaServiceReference.ConversionError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso {
            get {
                return this.ExitosoField;
            }
            set {
                if ((this.ExitosoField.Equals(value) != true)) {
                    this.ExitosoField = value;
                    this.RaisePropertyChanged("Exitoso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWebConversion.TemperaturaServiceReference.UnidadConversion Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionError", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    [System.SerializableAttribute()]
    public partial class ConversionError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetallesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ValorProblematicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoErrorField, value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalles {
            get {
                return this.DetallesField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesField, value) != true)) {
                    this.DetallesField = value;
                    this.RaisePropertyChanged("Detalles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaError {
            get {
                return this.FechaErrorField;
            }
            set {
                if ((this.FechaErrorField.Equals(value) != true)) {
                    this.FechaErrorField = value;
                    this.RaisePropertyChanged("FechaError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoError {
            get {
                return this.TipoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoErrorField, value) != true)) {
                    this.TipoErrorField = value;
                    this.RaisePropertyChanged("TipoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidad {
            get {
                return this.UnidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadField, value) != true)) {
                    this.UnidadField = value;
                    this.RaisePropertyChanged("Unidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValorProblematico {
            get {
                return this.ValorProblematicoField;
            }
            set {
                if ((this.ValorProblematicoField.Equals(value) != true)) {
                    this.ValorProblematicoField = value;
                    this.RaisePropertyChanged("ValorProblematico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadConversion", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    [System.SerializableAttribute()]
    public partial class UnidadConversion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FactorConversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaConversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorConvertidoExactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorConvertidoRedondeadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorOriginalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FactorConversion {
            get {
                return this.FactorConversionField;
            }
            set {
                if ((this.FactorConversionField.Equals(value) != true)) {
                    this.FactorConversionField = value;
                    this.RaisePropertyChanged("FactorConversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaConversion {
            get {
                return this.FechaConversionField;
            }
            set {
                if ((this.FechaConversionField.Equals(value) != true)) {
                    this.FechaConversionField = value;
                    this.RaisePropertyChanged("FechaConversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadDestino {
            get {
                return this.UnidadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadDestinoField, value) != true)) {
                    this.UnidadDestinoField = value;
                    this.RaisePropertyChanged("UnidadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadOrigen {
            get {
                return this.UnidadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadOrigenField, value) != true)) {
                    this.UnidadOrigenField = value;
                    this.RaisePropertyChanged("UnidadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertidoExacto {
            get {
                return this.ValorConvertidoExactoField;
            }
            set {
                if ((this.ValorConvertidoExactoField.Equals(value) != true)) {
                    this.ValorConvertidoExactoField = value;
                    this.RaisePropertyChanged("ValorConvertidoExacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertidoRedondeado {
            get {
                return this.ValorConvertidoRedondeadoField;
            }
            set {
                if ((this.ValorConvertidoRedondeadoField.Equals(value) != true)) {
                    this.ValorConvertidoRedondeadoField = value;
                    this.RaisePropertyChanged("ValorConvertidoRedondeado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorOriginal {
            get {
                return this.ValorOriginalField;
            }
            set {
                if ((this.ValorOriginalField.Equals(value) != true)) {
                    this.ValorOriginalField = value;
                    this.RaisePropertyChanged("ValorOriginal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TemperaturaServiceReference.ITemperaturaService")]
    public interface ITemperaturaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/ITemperaturaService/CelsiusAFahrenheitResponse")]
        ClienteWebConversion.TemperaturaServiceReference.ConversionResult CelsiusAFahrenheit(string celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/ITemperaturaService/CelsiusAFahrenheitResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.TemperaturaServiceReference.ConversionResult> CelsiusAFahrenheitAsync(string celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/FahrenheitACelsius", ReplyAction="http://tempuri.org/ITemperaturaService/FahrenheitACelsiusResponse")]
        ClienteWebConversion.TemperaturaServiceReference.ConversionResult FahrenheitACelsius(string fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/FahrenheitACelsius", ReplyAction="http://tempuri.org/ITemperaturaService/FahrenheitACelsiusResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.TemperaturaServiceReference.ConversionResult> FahrenheitACelsiusAsync(string fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/FahrenheitAKelvin", ReplyAction="http://tempuri.org/ITemperaturaService/FahrenheitAKelvinResponse")]
        ClienteWebConversion.TemperaturaServiceReference.ConversionResult FahrenheitAKelvin(string fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/FahrenheitAKelvin", ReplyAction="http://tempuri.org/ITemperaturaService/FahrenheitAKelvinResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.TemperaturaServiceReference.ConversionResult> FahrenheitAKelvinAsync(string fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/KelvinAFahrenheit", ReplyAction="http://tempuri.org/ITemperaturaService/KelvinAFahrenheitResponse")]
        ClienteWebConversion.TemperaturaServiceReference.ConversionResult KelvinAFahrenheit(string kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/KelvinAFahrenheit", ReplyAction="http://tempuri.org/ITemperaturaService/KelvinAFahrenheitResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.TemperaturaServiceReference.ConversionResult> KelvinAFahrenheitAsync(string kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/KelvinACelsius", ReplyAction="http://tempuri.org/ITemperaturaService/KelvinACelsiusResponse")]
        ClienteWebConversion.TemperaturaServiceReference.ConversionResult KelvinACelsius(string kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/KelvinACelsius", ReplyAction="http://tempuri.org/ITemperaturaService/KelvinACelsiusResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.TemperaturaServiceReference.ConversionResult> KelvinACelsiusAsync(string kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/CelsiusAKelvin", ReplyAction="http://tempuri.org/ITemperaturaService/CelsiusAKelvinResponse")]
        ClienteWebConversion.TemperaturaServiceReference.ConversionResult CelsiusAKelvin(string celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/CelsiusAKelvin", ReplyAction="http://tempuri.org/ITemperaturaService/CelsiusAKelvinResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.TemperaturaServiceReference.ConversionResult> CelsiusAKelvinAsync(string celsius);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITemperaturaServiceChannel : ClienteWebConversion.TemperaturaServiceReference.ITemperaturaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TemperaturaServiceClient : System.ServiceModel.ClientBase<ClienteWebConversion.TemperaturaServiceReference.ITemperaturaService>, ClienteWebConversion.TemperaturaServiceReference.ITemperaturaService {
        
        public TemperaturaServiceClient() {
        }
        
        public TemperaturaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TemperaturaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemperaturaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemperaturaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteWebConversion.TemperaturaServiceReference.ConversionResult CelsiusAFahrenheit(string celsius) {
            return base.Channel.CelsiusAFahrenheit(celsius);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.TemperaturaServiceReference.ConversionResult> CelsiusAFahrenheitAsync(string celsius) {
            return base.Channel.CelsiusAFahrenheitAsync(celsius);
        }
        
        public ClienteWebConversion.TemperaturaServiceReference.ConversionResult FahrenheitACelsius(string fahrenheit) {
            return base.Channel.FahrenheitACelsius(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.TemperaturaServiceReference.ConversionResult> FahrenheitACelsiusAsync(string fahrenheit) {
            return base.Channel.FahrenheitACelsiusAsync(fahrenheit);
        }
        
        public ClienteWebConversion.TemperaturaServiceReference.ConversionResult FahrenheitAKelvin(string fahrenheit) {
            return base.Channel.FahrenheitAKelvin(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.TemperaturaServiceReference.ConversionResult> FahrenheitAKelvinAsync(string fahrenheit) {
            return base.Channel.FahrenheitAKelvinAsync(fahrenheit);
        }
        
        public ClienteWebConversion.TemperaturaServiceReference.ConversionResult KelvinAFahrenheit(string kelvin) {
            return base.Channel.KelvinAFahrenheit(kelvin);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.TemperaturaServiceReference.ConversionResult> KelvinAFahrenheitAsync(string kelvin) {
            return base.Channel.KelvinAFahrenheitAsync(kelvin);
        }
        
        public ClienteWebConversion.TemperaturaServiceReference.ConversionResult KelvinACelsius(string kelvin) {
            return base.Channel.KelvinACelsius(kelvin);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.TemperaturaServiceReference.ConversionResult> KelvinACelsiusAsync(string kelvin) {
            return base.Channel.KelvinACelsiusAsync(kelvin);
        }
        
        public ClienteWebConversion.TemperaturaServiceReference.ConversionResult CelsiusAKelvin(string celsius) {
            return base.Channel.CelsiusAKelvin(celsius);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.TemperaturaServiceReference.ConversionResult> CelsiusAKelvinAsync(string celsius) {
            return base.Channel.CelsiusAKelvinAsync(celsius);
        }
    }
}
