//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetTemperatura
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionResult", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    public partial class ConversionResult : object
    {
        
        private DotNetTemperatura.ConversionError ErrorField;
        
        private bool ExitosoField;
        
        private DotNetTemperatura.UnidadConversion ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DotNetTemperatura.ConversionError Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso
        {
            get
            {
                return this.ExitosoField;
            }
            set
            {
                this.ExitosoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DotNetTemperatura.UnidadConversion Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionError", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    public partial class ConversionError : object
    {
        
        private string CodigoErrorField;
        
        private string DetallesField;
        
        private System.DateTime FechaErrorField;
        
        private string MensajeField;
        
        private string TipoErrorField;
        
        private string UnidadField;
        
        private System.Nullable<double> ValorProblematicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoError
        {
            get
            {
                return this.CodigoErrorField;
            }
            set
            {
                this.CodigoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalles
        {
            get
            {
                return this.DetallesField;
            }
            set
            {
                this.DetallesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaError
        {
            get
            {
                return this.FechaErrorField;
            }
            set
            {
                this.FechaErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoError
        {
            get
            {
                return this.TipoErrorField;
            }
            set
            {
                this.TipoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidad
        {
            get
            {
                return this.UnidadField;
            }
            set
            {
                this.UnidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValorProblematico
        {
            get
            {
                return this.ValorProblematicoField;
            }
            set
            {
                this.ValorProblematicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadConversion", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    public partial class UnidadConversion : object
    {
        
        private double FactorConversionField;
        
        private System.DateTime FechaConversionField;
        
        private string UnidadDestinoField;
        
        private string UnidadOrigenField;
        
        private double ValorConvertidoExactoField;
        
        private double ValorConvertidoRedondeadoField;
        
        private double ValorOriginalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FactorConversion
        {
            get
            {
                return this.FactorConversionField;
            }
            set
            {
                this.FactorConversionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaConversion
        {
            get
            {
                return this.FechaConversionField;
            }
            set
            {
                this.FechaConversionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadDestino
        {
            get
            {
                return this.UnidadDestinoField;
            }
            set
            {
                this.UnidadDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadOrigen
        {
            get
            {
                return this.UnidadOrigenField;
            }
            set
            {
                this.UnidadOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertidoExacto
        {
            get
            {
                return this.ValorConvertidoExactoField;
            }
            set
            {
                this.ValorConvertidoExactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertidoRedondeado
        {
            get
            {
                return this.ValorConvertidoRedondeadoField;
            }
            set
            {
                this.ValorConvertidoRedondeadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorOriginal
        {
            get
            {
                return this.ValorOriginalField;
            }
            set
            {
                this.ValorOriginalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DotNetTemperatura.ITemperaturaService")]
    public interface ITemperaturaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/ITemperaturaService/CelsiusAFahrenheitResponse")]
        System.Threading.Tasks.Task<DotNetTemperatura.ConversionResult> CelsiusAFahrenheitAsync(string celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/FahrenheitACelsius", ReplyAction="http://tempuri.org/ITemperaturaService/FahrenheitACelsiusResponse")]
        System.Threading.Tasks.Task<DotNetTemperatura.ConversionResult> FahrenheitACelsiusAsync(string fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/FahrenheitAKelvin", ReplyAction="http://tempuri.org/ITemperaturaService/FahrenheitAKelvinResponse")]
        System.Threading.Tasks.Task<DotNetTemperatura.ConversionResult> FahrenheitAKelvinAsync(string fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/KelvinAFahrenheit", ReplyAction="http://tempuri.org/ITemperaturaService/KelvinAFahrenheitResponse")]
        System.Threading.Tasks.Task<DotNetTemperatura.ConversionResult> KelvinAFahrenheitAsync(string kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/KelvinACelsius", ReplyAction="http://tempuri.org/ITemperaturaService/KelvinACelsiusResponse")]
        System.Threading.Tasks.Task<DotNetTemperatura.ConversionResult> KelvinACelsiusAsync(string kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperaturaService/CelsiusAKelvin", ReplyAction="http://tempuri.org/ITemperaturaService/CelsiusAKelvinResponse")]
        System.Threading.Tasks.Task<DotNetTemperatura.ConversionResult> CelsiusAKelvinAsync(string celsius);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ITemperaturaServiceChannel : DotNetTemperatura.ITemperaturaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TemperaturaServiceClient : System.ServiceModel.ClientBase<DotNetTemperatura.ITemperaturaService>, DotNetTemperatura.ITemperaturaService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TemperaturaServiceClient() : 
                base(TemperaturaServiceClient.GetDefaultBinding(), TemperaturaServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITemperaturaService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TemperaturaServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TemperaturaServiceClient.GetBindingForEndpoint(endpointConfiguration), TemperaturaServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TemperaturaServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TemperaturaServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TemperaturaServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TemperaturaServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TemperaturaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<DotNetTemperatura.ConversionResult> CelsiusAFahrenheitAsync(string celsius)
        {
            return base.Channel.CelsiusAFahrenheitAsync(celsius);
        }
        
        public System.Threading.Tasks.Task<DotNetTemperatura.ConversionResult> FahrenheitACelsiusAsync(string fahrenheit)
        {
            return base.Channel.FahrenheitACelsiusAsync(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<DotNetTemperatura.ConversionResult> FahrenheitAKelvinAsync(string fahrenheit)
        {
            return base.Channel.FahrenheitAKelvinAsync(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<DotNetTemperatura.ConversionResult> KelvinAFahrenheitAsync(string kelvin)
        {
            return base.Channel.KelvinAFahrenheitAsync(kelvin);
        }
        
        public System.Threading.Tasks.Task<DotNetTemperatura.ConversionResult> KelvinACelsiusAsync(string kelvin)
        {
            return base.Channel.KelvinACelsiusAsync(kelvin);
        }
        
        public System.Threading.Tasks.Task<DotNetTemperatura.ConversionResult> CelsiusAKelvinAsync(string celsius)
        {
            return base.Channel.CelsiusAKelvinAsync(celsius);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITemperaturaService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITemperaturaService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56686/ec/edu/monster/ws/TemperaturaService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TemperaturaServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITemperaturaService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TemperaturaServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITemperaturaService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITemperaturaService,
        }
    }
}
