//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavaMasa
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.monster.edu.ec/", ConfigurationName="JavaMasa.MasaService")]
    public interface MasaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/MasaService/KilogramoAQuintalRequest", ReplyAction="http://ws.monster.edu.ec/MasaService/KilogramoAQuintalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaMasa.KilogramoAQuintalResponse> KilogramoAQuintalAsync(JavaMasa.KilogramoAQuintalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/MasaService/KilogramoALibraRequest", ReplyAction="http://ws.monster.edu.ec/MasaService/KilogramoALibraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaMasa.KilogramoALibraResponse> KilogramoALibraAsync(JavaMasa.KilogramoALibraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/MasaService/LibraAKilogramoRequest", ReplyAction="http://ws.monster.edu.ec/MasaService/LibraAKilogramoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaMasa.LibraAKilogramoResponse> LibraAKilogramoAsync(JavaMasa.LibraAKilogramoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/MasaService/QuintalAKilogramoRequest", ReplyAction="http://ws.monster.edu.ec/MasaService/QuintalAKilogramoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaMasa.QuintalAKilogramoResponse> QuintalAKilogramoAsync(JavaMasa.QuintalAKilogramoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/MasaService/QuintalALibraRequest", ReplyAction="http://ws.monster.edu.ec/MasaService/QuintalALibraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaMasa.QuintalALibraResponse> QuintalALibraAsync(JavaMasa.QuintalALibraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/MasaService/LibraAQuintalRequest", ReplyAction="http://ws.monster.edu.ec/MasaService/LibraAQuintalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaMasa.LibraAQuintalResponse> LibraAQuintalAsync(JavaMasa.LibraAQuintalRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class conversionResult
    {
        
        private bool exitosoField;
        
        private unidadConversion resultadoField;
        
        private conversionError errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool Exitoso
        {
            get
            {
                return this.exitosoField;
            }
            set
            {
                this.exitosoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public unidadConversion Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public conversionError Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class unidadConversion
    {
        
        private double valorOriginalField;
        
        private double valorConvertidoExactoField;
        
        private double valorConvertidoRedondeadoField;
        
        private string unidadOrigenField;
        
        private string unidadDestinoField;
        
        private double factorConversionField;
        
        private localDateTime fechaConversionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double valorOriginal
        {
            get
            {
                return this.valorOriginalField;
            }
            set
            {
                this.valorOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double valorConvertidoExacto
        {
            get
            {
                return this.valorConvertidoExactoField;
            }
            set
            {
                this.valorConvertidoExactoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double valorConvertidoRedondeado
        {
            get
            {
                return this.valorConvertidoRedondeadoField;
            }
            set
            {
                this.valorConvertidoRedondeadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string unidadOrigen
        {
            get
            {
                return this.unidadOrigenField;
            }
            set
            {
                this.unidadOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string unidadDestino
        {
            get
            {
                return this.unidadDestinoField;
            }
            set
            {
                this.unidadDestinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double factorConversion
        {
            get
            {
                return this.factorConversionField;
            }
            set
            {
                this.factorConversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public localDateTime fechaConversion
        {
            get
            {
                return this.fechaConversionField;
            }
            set
            {
                this.fechaConversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class localDateTime
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class conversionError
    {
        
        private string codigoErrorField;
        
        private string mensajeField;
        
        private string tipoErrorField;
        
        private double valorProblematicoField;
        
        private bool valorProblematicoFieldSpecified;
        
        private string unidadField;
        
        private localDateTime fechaErrorField;
        
        private string detallesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TipoError
        {
            get
            {
                return this.tipoErrorField;
            }
            set
            {
                this.tipoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double ValorProblematico
        {
            get
            {
                return this.valorProblematicoField;
            }
            set
            {
                this.valorProblematicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorProblematicoSpecified
        {
            get
            {
                return this.valorProblematicoFieldSpecified;
            }
            set
            {
                this.valorProblematicoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Unidad
        {
            get
            {
                return this.unidadField;
            }
            set
            {
                this.unidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public localDateTime FechaError
        {
            get
            {
                return this.fechaErrorField;
            }
            set
            {
                this.fechaErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Detalles
        {
            get
            {
                return this.detallesField;
            }
            set
            {
                this.detallesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KilogramoAQuintal", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class KilogramoAQuintalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kilogramos;
        
        public KilogramoAQuintalRequest()
        {
        }
        
        public KilogramoAQuintalRequest(string kilogramos)
        {
            this.kilogramos = kilogramos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KilogramoAQuintalResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class KilogramoAQuintalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaMasa.conversionResult @return;
        
        public KilogramoAQuintalResponse()
        {
        }
        
        public KilogramoAQuintalResponse(JavaMasa.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KilogramoALibra", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class KilogramoALibraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kilogramos;
        
        public KilogramoALibraRequest()
        {
        }
        
        public KilogramoALibraRequest(string kilogramos)
        {
            this.kilogramos = kilogramos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KilogramoALibraResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class KilogramoALibraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaMasa.conversionResult @return;
        
        public KilogramoALibraResponse()
        {
        }
        
        public KilogramoALibraResponse(JavaMasa.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LibraAKilogramo", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class LibraAKilogramoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string libras;
        
        public LibraAKilogramoRequest()
        {
        }
        
        public LibraAKilogramoRequest(string libras)
        {
            this.libras = libras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LibraAKilogramoResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class LibraAKilogramoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaMasa.conversionResult @return;
        
        public LibraAKilogramoResponse()
        {
        }
        
        public LibraAKilogramoResponse(JavaMasa.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QuintalAKilogramo", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class QuintalAKilogramoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string quintales;
        
        public QuintalAKilogramoRequest()
        {
        }
        
        public QuintalAKilogramoRequest(string quintales)
        {
            this.quintales = quintales;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QuintalAKilogramoResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class QuintalAKilogramoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaMasa.conversionResult @return;
        
        public QuintalAKilogramoResponse()
        {
        }
        
        public QuintalAKilogramoResponse(JavaMasa.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QuintalALibra", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class QuintalALibraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string quintales;
        
        public QuintalALibraRequest()
        {
        }
        
        public QuintalALibraRequest(string quintales)
        {
            this.quintales = quintales;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QuintalALibraResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class QuintalALibraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaMasa.conversionResult @return;
        
        public QuintalALibraResponse()
        {
        }
        
        public QuintalALibraResponse(JavaMasa.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LibraAQuintal", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class LibraAQuintalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string libras;
        
        public LibraAQuintalRequest()
        {
        }
        
        public LibraAQuintalRequest(string libras)
        {
            this.libras = libras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LibraAQuintalResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class LibraAQuintalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaMasa.conversionResult @return;
        
        public LibraAQuintalResponse()
        {
        }
        
        public LibraAQuintalResponse(JavaMasa.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface MasaServiceChannel : JavaMasa.MasaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class MasaServiceClient : System.ServiceModel.ClientBase<JavaMasa.MasaService>, JavaMasa.MasaService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MasaServiceClient() : 
                base(MasaServiceClient.GetDefaultBinding(), MasaServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MasaServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MasaServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MasaServiceClient.GetBindingForEndpoint(endpointConfiguration), MasaServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MasaServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MasaServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MasaServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MasaServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MasaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaMasa.KilogramoAQuintalResponse> JavaMasa.MasaService.KilogramoAQuintalAsync(JavaMasa.KilogramoAQuintalRequest request)
        {
            return base.Channel.KilogramoAQuintalAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaMasa.KilogramoAQuintalResponse> KilogramoAQuintalAsync(string kilogramos)
        {
            JavaMasa.KilogramoAQuintalRequest inValue = new JavaMasa.KilogramoAQuintalRequest();
            inValue.kilogramos = kilogramos;
            return ((JavaMasa.MasaService)(this)).KilogramoAQuintalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaMasa.KilogramoALibraResponse> JavaMasa.MasaService.KilogramoALibraAsync(JavaMasa.KilogramoALibraRequest request)
        {
            return base.Channel.KilogramoALibraAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaMasa.KilogramoALibraResponse> KilogramoALibraAsync(string kilogramos)
        {
            JavaMasa.KilogramoALibraRequest inValue = new JavaMasa.KilogramoALibraRequest();
            inValue.kilogramos = kilogramos;
            return ((JavaMasa.MasaService)(this)).KilogramoALibraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaMasa.LibraAKilogramoResponse> JavaMasa.MasaService.LibraAKilogramoAsync(JavaMasa.LibraAKilogramoRequest request)
        {
            return base.Channel.LibraAKilogramoAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaMasa.LibraAKilogramoResponse> LibraAKilogramoAsync(string libras)
        {
            JavaMasa.LibraAKilogramoRequest inValue = new JavaMasa.LibraAKilogramoRequest();
            inValue.libras = libras;
            return ((JavaMasa.MasaService)(this)).LibraAKilogramoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaMasa.QuintalAKilogramoResponse> JavaMasa.MasaService.QuintalAKilogramoAsync(JavaMasa.QuintalAKilogramoRequest request)
        {
            return base.Channel.QuintalAKilogramoAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaMasa.QuintalAKilogramoResponse> QuintalAKilogramoAsync(string quintales)
        {
            JavaMasa.QuintalAKilogramoRequest inValue = new JavaMasa.QuintalAKilogramoRequest();
            inValue.quintales = quintales;
            return ((JavaMasa.MasaService)(this)).QuintalAKilogramoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaMasa.QuintalALibraResponse> JavaMasa.MasaService.QuintalALibraAsync(JavaMasa.QuintalALibraRequest request)
        {
            return base.Channel.QuintalALibraAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaMasa.QuintalALibraResponse> QuintalALibraAsync(string quintales)
        {
            JavaMasa.QuintalALibraRequest inValue = new JavaMasa.QuintalALibraRequest();
            inValue.quintales = quintales;
            return ((JavaMasa.MasaService)(this)).QuintalALibraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaMasa.LibraAQuintalResponse> JavaMasa.MasaService.LibraAQuintalAsync(JavaMasa.LibraAQuintalRequest request)
        {
            return base.Channel.LibraAQuintalAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaMasa.LibraAQuintalResponse> LibraAQuintalAsync(string libras)
        {
            JavaMasa.LibraAQuintalRequest inValue = new JavaMasa.LibraAQuintalRequest();
            inValue.libras = libras;
            return ((JavaMasa.MasaService)(this)).LibraAQuintalAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MasaServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MasaServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/ConUni_Soap_Java_GR01/MasaService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MasaServiceClient.GetBindingForEndpoint(EndpointConfiguration.MasaServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MasaServiceClient.GetEndpointAddress(EndpointConfiguration.MasaServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            MasaServicePort,
        }
    }
}
