//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebConversion.LongitudServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionResult", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    [System.SerializableAttribute()]
    public partial class ConversionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWebConversion.LongitudServiceReference.ConversionError ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitosoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWebConversion.LongitudServiceReference.UnidadConversion ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWebConversion.LongitudServiceReference.ConversionError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso {
            get {
                return this.ExitosoField;
            }
            set {
                if ((this.ExitosoField.Equals(value) != true)) {
                    this.ExitosoField = value;
                    this.RaisePropertyChanged("Exitoso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWebConversion.LongitudServiceReference.UnidadConversion Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionError", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    [System.SerializableAttribute()]
    public partial class ConversionError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetallesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ValorProblematicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoErrorField, value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalles {
            get {
                return this.DetallesField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesField, value) != true)) {
                    this.DetallesField = value;
                    this.RaisePropertyChanged("Detalles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaError {
            get {
                return this.FechaErrorField;
            }
            set {
                if ((this.FechaErrorField.Equals(value) != true)) {
                    this.FechaErrorField = value;
                    this.RaisePropertyChanged("FechaError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoError {
            get {
                return this.TipoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoErrorField, value) != true)) {
                    this.TipoErrorField = value;
                    this.RaisePropertyChanged("TipoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidad {
            get {
                return this.UnidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadField, value) != true)) {
                    this.UnidadField = value;
                    this.RaisePropertyChanged("Unidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValorProblematico {
            get {
                return this.ValorProblematicoField;
            }
            set {
                if ((this.ValorProblematicoField.Equals(value) != true)) {
                    this.ValorProblematicoField = value;
                    this.RaisePropertyChanged("ValorProblematico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadConversion", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_DotNet_GR01.ec.edu.monster.mo" +
        "dels")]
    [System.SerializableAttribute()]
    public partial class UnidadConversion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FactorConversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaConversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorConvertidoExactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorConvertidoRedondeadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorOriginalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FactorConversion {
            get {
                return this.FactorConversionField;
            }
            set {
                if ((this.FactorConversionField.Equals(value) != true)) {
                    this.FactorConversionField = value;
                    this.RaisePropertyChanged("FactorConversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaConversion {
            get {
                return this.FechaConversionField;
            }
            set {
                if ((this.FechaConversionField.Equals(value) != true)) {
                    this.FechaConversionField = value;
                    this.RaisePropertyChanged("FechaConversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadDestino {
            get {
                return this.UnidadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadDestinoField, value) != true)) {
                    this.UnidadDestinoField = value;
                    this.RaisePropertyChanged("UnidadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadOrigen {
            get {
                return this.UnidadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadOrigenField, value) != true)) {
                    this.UnidadOrigenField = value;
                    this.RaisePropertyChanged("UnidadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertidoExacto {
            get {
                return this.ValorConvertidoExactoField;
            }
            set {
                if ((this.ValorConvertidoExactoField.Equals(value) != true)) {
                    this.ValorConvertidoExactoField = value;
                    this.RaisePropertyChanged("ValorConvertidoExacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertidoRedondeado {
            get {
                return this.ValorConvertidoRedondeadoField;
            }
            set {
                if ((this.ValorConvertidoRedondeadoField.Equals(value) != true)) {
                    this.ValorConvertidoRedondeadoField = value;
                    this.RaisePropertyChanged("ValorConvertidoRedondeado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorOriginal {
            get {
                return this.ValorOriginalField;
            }
            set {
                if ((this.ValorOriginalField.Equals(value) != true)) {
                    this.ValorOriginalField = value;
                    this.RaisePropertyChanged("ValorOriginal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LongitudServiceReference.ILongitudService")]
    public interface ILongitudService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/MillaAMetro", ReplyAction="http://tempuri.org/ILongitudService/MillaAMetroResponse")]
        ClienteWebConversion.LongitudServiceReference.ConversionResult MillaAMetro(string millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/MillaAMetro", ReplyAction="http://tempuri.org/ILongitudService/MillaAMetroResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.LongitudServiceReference.ConversionResult> MillaAMetroAsync(string millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/MetroAMilla", ReplyAction="http://tempuri.org/ILongitudService/MetroAMillaResponse")]
        ClienteWebConversion.LongitudServiceReference.ConversionResult MetroAMilla(string metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/MetroAMilla", ReplyAction="http://tempuri.org/ILongitudService/MetroAMillaResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.LongitudServiceReference.ConversionResult> MetroAMillaAsync(string metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/MillaAPulgada", ReplyAction="http://tempuri.org/ILongitudService/MillaAPulgadaResponse")]
        ClienteWebConversion.LongitudServiceReference.ConversionResult MillaAPulgada(string millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/MillaAPulgada", ReplyAction="http://tempuri.org/ILongitudService/MillaAPulgadaResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.LongitudServiceReference.ConversionResult> MillaAPulgadaAsync(string millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/PulgadaAMilla", ReplyAction="http://tempuri.org/ILongitudService/PulgadaAMillaResponse")]
        ClienteWebConversion.LongitudServiceReference.ConversionResult PulgadaAMilla(string pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/PulgadaAMilla", ReplyAction="http://tempuri.org/ILongitudService/PulgadaAMillaResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.LongitudServiceReference.ConversionResult> PulgadaAMillaAsync(string pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/MetroAPulgada", ReplyAction="http://tempuri.org/ILongitudService/MetroAPulgadaResponse")]
        ClienteWebConversion.LongitudServiceReference.ConversionResult MetroAPulgada(string metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/MetroAPulgada", ReplyAction="http://tempuri.org/ILongitudService/MetroAPulgadaResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.LongitudServiceReference.ConversionResult> MetroAPulgadaAsync(string metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/PulgadaAMetro", ReplyAction="http://tempuri.org/ILongitudService/PulgadaAMetroResponse")]
        ClienteWebConversion.LongitudServiceReference.ConversionResult PulgadaAMetro(string pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongitudService/PulgadaAMetro", ReplyAction="http://tempuri.org/ILongitudService/PulgadaAMetroResponse")]
        System.Threading.Tasks.Task<ClienteWebConversion.LongitudServiceReference.ConversionResult> PulgadaAMetroAsync(string pulgadas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILongitudServiceChannel : ClienteWebConversion.LongitudServiceReference.ILongitudService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LongitudServiceClient : System.ServiceModel.ClientBase<ClienteWebConversion.LongitudServiceReference.ILongitudService>, ClienteWebConversion.LongitudServiceReference.ILongitudService {
        
        public LongitudServiceClient() {
        }
        
        public LongitudServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LongitudServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LongitudServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LongitudServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteWebConversion.LongitudServiceReference.ConversionResult MillaAMetro(string millas) {
            return base.Channel.MillaAMetro(millas);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.LongitudServiceReference.ConversionResult> MillaAMetroAsync(string millas) {
            return base.Channel.MillaAMetroAsync(millas);
        }
        
        public ClienteWebConversion.LongitudServiceReference.ConversionResult MetroAMilla(string metros) {
            return base.Channel.MetroAMilla(metros);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.LongitudServiceReference.ConversionResult> MetroAMillaAsync(string metros) {
            return base.Channel.MetroAMillaAsync(metros);
        }
        
        public ClienteWebConversion.LongitudServiceReference.ConversionResult MillaAPulgada(string millas) {
            return base.Channel.MillaAPulgada(millas);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.LongitudServiceReference.ConversionResult> MillaAPulgadaAsync(string millas) {
            return base.Channel.MillaAPulgadaAsync(millas);
        }
        
        public ClienteWebConversion.LongitudServiceReference.ConversionResult PulgadaAMilla(string pulgadas) {
            return base.Channel.PulgadaAMilla(pulgadas);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.LongitudServiceReference.ConversionResult> PulgadaAMillaAsync(string pulgadas) {
            return base.Channel.PulgadaAMillaAsync(pulgadas);
        }
        
        public ClienteWebConversion.LongitudServiceReference.ConversionResult MetroAPulgada(string metros) {
            return base.Channel.MetroAPulgada(metros);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.LongitudServiceReference.ConversionResult> MetroAPulgadaAsync(string metros) {
            return base.Channel.MetroAPulgadaAsync(metros);
        }
        
        public ClienteWebConversion.LongitudServiceReference.ConversionResult PulgadaAMetro(string pulgadas) {
            return base.Channel.PulgadaAMetro(pulgadas);
        }
        
        public System.Threading.Tasks.Task<ClienteWebConversion.LongitudServiceReference.ConversionResult> PulgadaAMetroAsync(string pulgadas) {
            return base.Channel.PulgadaAMetroAsync(pulgadas);
        }
    }
}
