//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConUni_CliEsc_GR01.LongitudServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.monster.edu.ec/", ConfigurationName="ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService")]
    public interface LongitudService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/LongitudService/MetroAMillaRequest", ReplyAction="http://ws.monster.edu.ec/LongitudService/MetroAMillaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.MetroAMillaResponse> MetroAMillaAsync(ConUni_CliEsc_GR01.LongitudServiceReference.MetroAMillaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/LongitudService/MillaAMetroRequest", ReplyAction="http://ws.monster.edu.ec/LongitudService/MillaAMetroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.MillaAMetroResponse> MillaAMetroAsync(ConUni_CliEsc_GR01.LongitudServiceReference.MillaAMetroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/LongitudService/PulgadaAMetroRequest", ReplyAction="http://ws.monster.edu.ec/LongitudService/PulgadaAMetroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMetroResponse> PulgadaAMetroAsync(ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMetroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/LongitudService/PulgadaAMillaRequest", ReplyAction="http://ws.monster.edu.ec/LongitudService/PulgadaAMillaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMillaResponse> PulgadaAMillaAsync(ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMillaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/LongitudService/MetroAPulgadaRequest", ReplyAction="http://ws.monster.edu.ec/LongitudService/MetroAPulgadaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.MetroAPulgadaResponse> MetroAPulgadaAsync(ConUni_CliEsc_GR01.LongitudServiceReference.MetroAPulgadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/LongitudService/MillaAPulgadaRequest", ReplyAction="http://ws.monster.edu.ec/LongitudService/MillaAPulgadaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.MillaAPulgadaResponse> MillaAPulgadaAsync(ConUni_CliEsc_GR01.LongitudServiceReference.MillaAPulgadaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class conversionResult
    {
        
        private bool exitosoField;
        
        private unidadConversion resultadoField;
        
        private conversionError errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool Exitoso
        {
            get
            {
                return this.exitosoField;
            }
            set
            {
                this.exitosoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public unidadConversion Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public conversionError Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class unidadConversion
    {
        
        private double valorOriginalField;
        
        private double valorConvertidoExactoField;
        
        private double valorConvertidoRedondeadoField;
        
        private string unidadOrigenField;
        
        private string unidadDestinoField;
        
        private double factorConversionField;
        
        private localDateTime fechaConversionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double valorOriginal
        {
            get
            {
                return this.valorOriginalField;
            }
            set
            {
                this.valorOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double valorConvertidoExacto
        {
            get
            {
                return this.valorConvertidoExactoField;
            }
            set
            {
                this.valorConvertidoExactoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double valorConvertidoRedondeado
        {
            get
            {
                return this.valorConvertidoRedondeadoField;
            }
            set
            {
                this.valorConvertidoRedondeadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string unidadOrigen
        {
            get
            {
                return this.unidadOrigenField;
            }
            set
            {
                this.unidadOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string unidadDestino
        {
            get
            {
                return this.unidadDestinoField;
            }
            set
            {
                this.unidadDestinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double factorConversion
        {
            get
            {
                return this.factorConversionField;
            }
            set
            {
                this.factorConversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public localDateTime fechaConversion
        {
            get
            {
                return this.fechaConversionField;
            }
            set
            {
                this.fechaConversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class localDateTime
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class conversionError
    {
        
        private string codigoErrorField;
        
        private string mensajeField;
        
        private string tipoErrorField;
        
        private double valorProblematicoField;
        
        private bool valorProblematicoFieldSpecified;
        
        private string unidadField;
        
        private localDateTime fechaErrorField;
        
        private string detallesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TipoError
        {
            get
            {
                return this.tipoErrorField;
            }
            set
            {
                this.tipoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double ValorProblematico
        {
            get
            {
                return this.valorProblematicoField;
            }
            set
            {
                this.valorProblematicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorProblematicoSpecified
        {
            get
            {
                return this.valorProblematicoFieldSpecified;
            }
            set
            {
                this.valorProblematicoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Unidad
        {
            get
            {
                return this.unidadField;
            }
            set
            {
                this.unidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public localDateTime FechaError
        {
            get
            {
                return this.fechaErrorField;
            }
            set
            {
                this.fechaErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Detalles
        {
            get
            {
                return this.detallesField;
            }
            set
            {
                this.detallesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MetroAMilla", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class MetroAMillaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metros;
        
        public MetroAMillaRequest()
        {
        }
        
        public MetroAMillaRequest(string metros)
        {
            this.metros = metros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MetroAMillaResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class MetroAMillaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConUni_CliEsc_GR01.LongitudServiceReference.conversionResult @return;
        
        public MetroAMillaResponse()
        {
        }
        
        public MetroAMillaResponse(ConUni_CliEsc_GR01.LongitudServiceReference.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MillaAMetro", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class MillaAMetroRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string millas;
        
        public MillaAMetroRequest()
        {
        }
        
        public MillaAMetroRequest(string millas)
        {
            this.millas = millas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MillaAMetroResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class MillaAMetroResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConUni_CliEsc_GR01.LongitudServiceReference.conversionResult @return;
        
        public MillaAMetroResponse()
        {
        }
        
        public MillaAMetroResponse(ConUni_CliEsc_GR01.LongitudServiceReference.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PulgadaAMetro", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class PulgadaAMetroRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pulgadas;
        
        public PulgadaAMetroRequest()
        {
        }
        
        public PulgadaAMetroRequest(string pulgadas)
        {
            this.pulgadas = pulgadas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PulgadaAMetroResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class PulgadaAMetroResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConUni_CliEsc_GR01.LongitudServiceReference.conversionResult @return;
        
        public PulgadaAMetroResponse()
        {
        }
        
        public PulgadaAMetroResponse(ConUni_CliEsc_GR01.LongitudServiceReference.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PulgadaAMilla", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class PulgadaAMillaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pulgadas;
        
        public PulgadaAMillaRequest()
        {
        }
        
        public PulgadaAMillaRequest(string pulgadas)
        {
            this.pulgadas = pulgadas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PulgadaAMillaResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class PulgadaAMillaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConUni_CliEsc_GR01.LongitudServiceReference.conversionResult @return;
        
        public PulgadaAMillaResponse()
        {
        }
        
        public PulgadaAMillaResponse(ConUni_CliEsc_GR01.LongitudServiceReference.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MetroAPulgada", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class MetroAPulgadaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metros;
        
        public MetroAPulgadaRequest()
        {
        }
        
        public MetroAPulgadaRequest(string metros)
        {
            this.metros = metros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MetroAPulgadaResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class MetroAPulgadaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConUni_CliEsc_GR01.LongitudServiceReference.conversionResult @return;
        
        public MetroAPulgadaResponse()
        {
        }
        
        public MetroAPulgadaResponse(ConUni_CliEsc_GR01.LongitudServiceReference.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MillaAPulgada", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class MillaAPulgadaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string millas;
        
        public MillaAPulgadaRequest()
        {
        }
        
        public MillaAPulgadaRequest(string millas)
        {
            this.millas = millas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MillaAPulgadaResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class MillaAPulgadaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConUni_CliEsc_GR01.LongitudServiceReference.conversionResult @return;
        
        public MillaAPulgadaResponse()
        {
        }
        
        public MillaAPulgadaResponse(ConUni_CliEsc_GR01.LongitudServiceReference.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface LongitudServiceChannel : ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class LongitudServiceClient : System.ServiceModel.ClientBase<ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService>, ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LongitudServiceClient() : 
                base(LongitudServiceClient.GetDefaultBinding(), LongitudServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.LongitudServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LongitudServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LongitudServiceClient.GetBindingForEndpoint(endpointConfiguration), LongitudServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LongitudServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LongitudServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LongitudServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LongitudServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LongitudServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.MetroAMillaResponse> ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService.MetroAMillaAsync(ConUni_CliEsc_GR01.LongitudServiceReference.MetroAMillaRequest request)
        {
            return base.Channel.MetroAMillaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.MetroAMillaResponse> MetroAMillaAsync(string metros)
        {
            ConUni_CliEsc_GR01.LongitudServiceReference.MetroAMillaRequest inValue = new ConUni_CliEsc_GR01.LongitudServiceReference.MetroAMillaRequest();
            inValue.metros = metros;
            return ((ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService)(this)).MetroAMillaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.MillaAMetroResponse> ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService.MillaAMetroAsync(ConUni_CliEsc_GR01.LongitudServiceReference.MillaAMetroRequest request)
        {
            return base.Channel.MillaAMetroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.MillaAMetroResponse> MillaAMetroAsync(string millas)
        {
            ConUni_CliEsc_GR01.LongitudServiceReference.MillaAMetroRequest inValue = new ConUni_CliEsc_GR01.LongitudServiceReference.MillaAMetroRequest();
            inValue.millas = millas;
            return ((ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService)(this)).MillaAMetroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMetroResponse> ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService.PulgadaAMetroAsync(ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMetroRequest request)
        {
            return base.Channel.PulgadaAMetroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMetroResponse> PulgadaAMetroAsync(string pulgadas)
        {
            ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMetroRequest inValue = new ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMetroRequest();
            inValue.pulgadas = pulgadas;
            return ((ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService)(this)).PulgadaAMetroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMillaResponse> ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService.PulgadaAMillaAsync(ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMillaRequest request)
        {
            return base.Channel.PulgadaAMillaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMillaResponse> PulgadaAMillaAsync(string pulgadas)
        {
            ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMillaRequest inValue = new ConUni_CliEsc_GR01.LongitudServiceReference.PulgadaAMillaRequest();
            inValue.pulgadas = pulgadas;
            return ((ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService)(this)).PulgadaAMillaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.MetroAPulgadaResponse> ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService.MetroAPulgadaAsync(ConUni_CliEsc_GR01.LongitudServiceReference.MetroAPulgadaRequest request)
        {
            return base.Channel.MetroAPulgadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.MetroAPulgadaResponse> MetroAPulgadaAsync(string metros)
        {
            ConUni_CliEsc_GR01.LongitudServiceReference.MetroAPulgadaRequest inValue = new ConUni_CliEsc_GR01.LongitudServiceReference.MetroAPulgadaRequest();
            inValue.metros = metros;
            return ((ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService)(this)).MetroAPulgadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.MillaAPulgadaResponse> ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService.MillaAPulgadaAsync(ConUni_CliEsc_GR01.LongitudServiceReference.MillaAPulgadaRequest request)
        {
            return base.Channel.MillaAPulgadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.LongitudServiceReference.MillaAPulgadaResponse> MillaAPulgadaAsync(string millas)
        {
            ConUni_CliEsc_GR01.LongitudServiceReference.MillaAPulgadaRequest inValue = new ConUni_CliEsc_GR01.LongitudServiceReference.MillaAPulgadaRequest();
            inValue.millas = millas;
            return ((ConUni_CliEsc_GR01.LongitudServiceReference.LongitudService)(this)).MillaAPulgadaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LongitudServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LongitudServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/ConUni_Soap_Java_GR01/LongitudService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LongitudServiceClient.GetBindingForEndpoint(EndpointConfiguration.LongitudServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LongitudServiceClient.GetEndpointAddress(EndpointConfiguration.LongitudServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            LongitudServicePort,
        }
    }
}
