//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercializadoraSoapProducts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrearProductoDTO", Namespace="http://schemas.datacontract.org/2004/07/Comercializadora_Soap_DotNet_GR01.DTOs")]
    public partial class CrearProductoDTO : object
    {
        
        private string CodigoField;
        
        private string NombreField;
        
        private string DescripcionField;
        
        private decimal PrecioField;
        
        private int StockField;
        
        private string CategoriaField;
        
        private string ImagenUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Precio
        {
            get
            {
                return this.PrecioField;
            }
            set
            {
                this.PrecioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ImagenUrl
        {
            get
            {
                return this.ImagenUrlField;
            }
            set
            {
                this.ImagenUrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaDTO", Namespace="http://schemas.datacontract.org/2004/07/Comercializadora_Soap_DotNet_GR01.DTOs")]
    public partial class RespuestaDTO : object
    {
        
        private ComercializadoraSoapProducts.ProductoDTO DatosField;
        
        private bool ExitoField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ComercializadoraSoapProducts.ProductoDTO Datos
        {
            get
            {
                return this.DatosField;
            }
            set
            {
                this.DatosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito
        {
            get
            {
                return this.ExitoField;
            }
            set
            {
                this.ExitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDTO", Namespace="http://schemas.datacontract.org/2004/07/Comercializadora_Soap_DotNet_GR01.DTOs")]
    public partial class ProductoDTO : object
    {
        
        private int ProductoIdField;
        
        private string CodigoField;
        
        private string NombreField;
        
        private string DescripcionField;
        
        private decimal PrecioField;
        
        private int StockField;
        
        private string CategoriaField;
        
        private string ImagenUrlField;
        
        private System.DateTime FechaRegistroField;
        
        private string EstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductoId
        {
            get
            {
                return this.ProductoIdField;
            }
            set
            {
                this.ProductoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal Precio
        {
            get
            {
                return this.PrecioField;
            }
            set
            {
                this.PrecioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string ImagenUrl
        {
            get
            {
                return this.ImagenUrlField;
            }
            set
            {
                this.ImagenUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActualizarProductoDTO", Namespace="http://schemas.datacontract.org/2004/07/Comercializadora_Soap_DotNet_GR01.DTOs")]
    public partial class ActualizarProductoDTO : object
    {
        
        private int ProductoIdField;
        
        private string CodigoField;
        
        private string NombreField;
        
        private string DescripcionField;
        
        private decimal PrecioField;
        
        private int StockField;
        
        private string CategoriaField;
        
        private string ImagenUrlField;
        
        private string EstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductoId
        {
            get
            {
                return this.ProductoIdField;
            }
            set
            {
                this.ProductoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal Precio
        {
            get
            {
                return this.PrecioField;
            }
            set
            {
                this.PrecioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string ImagenUrl
        {
            get
            {
                return this.ImagenUrlField;
            }
            set
            {
                this.ImagenUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComercializadoraSoapProducts.IProductoSoapService")]
    public interface IProductoSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoSoapService/CrearProducto", ReplyAction="http://tempuri.org/IProductoSoapService/CrearProductoResponse")]
        System.Threading.Tasks.Task<ComercializadoraSoapProducts.RespuestaDTO> CrearProductoAsync(ComercializadoraSoapProducts.CrearProductoDTO producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoSoapService/ObtenerProductos", ReplyAction="http://tempuri.org/IProductoSoapService/ObtenerProductosResponse")]
        System.Threading.Tasks.Task<ComercializadoraSoapProducts.ProductoDTO[]> ObtenerProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoSoapService/ObtenerProductoPorId", ReplyAction="http://tempuri.org/IProductoSoapService/ObtenerProductoPorIdResponse")]
        System.Threading.Tasks.Task<ComercializadoraSoapProducts.ProductoDTO> ObtenerProductoPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoSoapService/ObtenerProductoPorCodigo", ReplyAction="http://tempuri.org/IProductoSoapService/ObtenerProductoPorCodigoResponse")]
        System.Threading.Tasks.Task<ComercializadoraSoapProducts.ProductoDTO> ObtenerProductoPorCodigoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoSoapService/ObtenerProductosPorCategoria", ReplyAction="http://tempuri.org/IProductoSoapService/ObtenerProductosPorCategoriaResponse")]
        System.Threading.Tasks.Task<ComercializadoraSoapProducts.ProductoDTO[]> ObtenerProductosPorCategoriaAsync(string categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoSoapService/ObtenerProductosPorPrecio", ReplyAction="http://tempuri.org/IProductoSoapService/ObtenerProductosPorPrecioResponse")]
        System.Threading.Tasks.Task<ComercializadoraSoapProducts.ProductoDTO[]> ObtenerProductosPorPrecioAsync(decimal precioMin, decimal precioMax);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoSoapService/ActualizarProducto", ReplyAction="http://tempuri.org/IProductoSoapService/ActualizarProductoResponse")]
        System.Threading.Tasks.Task<ComercializadoraSoapProducts.RespuestaDTO> ActualizarProductoAsync(ComercializadoraSoapProducts.ActualizarProductoDTO producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoSoapService/EliminarProducto", ReplyAction="http://tempuri.org/IProductoSoapService/EliminarProductoResponse")]
        System.Threading.Tasks.Task<ComercializadoraSoapProducts.RespuestaDTO> EliminarProductoAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IProductoSoapServiceChannel : ComercializadoraSoapProducts.IProductoSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ProductoSoapServiceClient : System.ServiceModel.ClientBase<ComercializadoraSoapProducts.IProductoSoapService>, ComercializadoraSoapProducts.IProductoSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProductoSoapServiceClient() : 
                base(ProductoSoapServiceClient.GetDefaultBinding(), ProductoSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IProductoSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductoSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ProductoSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), ProductoSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductoSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProductoSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductoSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProductoSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductoSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ComercializadoraSoapProducts.RespuestaDTO> CrearProductoAsync(ComercializadoraSoapProducts.CrearProductoDTO producto)
        {
            return base.Channel.CrearProductoAsync(producto);
        }
        
        public System.Threading.Tasks.Task<ComercializadoraSoapProducts.ProductoDTO[]> ObtenerProductosAsync()
        {
            return base.Channel.ObtenerProductosAsync();
        }
        
        public System.Threading.Tasks.Task<ComercializadoraSoapProducts.ProductoDTO> ObtenerProductoPorIdAsync(int id)
        {
            return base.Channel.ObtenerProductoPorIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ComercializadoraSoapProducts.ProductoDTO> ObtenerProductoPorCodigoAsync(string codigo)
        {
            return base.Channel.ObtenerProductoPorCodigoAsync(codigo);
        }
        
        public System.Threading.Tasks.Task<ComercializadoraSoapProducts.ProductoDTO[]> ObtenerProductosPorCategoriaAsync(string categoria)
        {
            return base.Channel.ObtenerProductosPorCategoriaAsync(categoria);
        }
        
        public System.Threading.Tasks.Task<ComercializadoraSoapProducts.ProductoDTO[]> ObtenerProductosPorPrecioAsync(decimal precioMin, decimal precioMax)
        {
            return base.Channel.ObtenerProductosPorPrecioAsync(precioMin, precioMax);
        }
        
        public System.Threading.Tasks.Task<ComercializadoraSoapProducts.RespuestaDTO> ActualizarProductoAsync(ComercializadoraSoapProducts.ActualizarProductoDTO producto)
        {
            return base.Channel.ActualizarProductoAsync(producto);
        }
        
        public System.Threading.Tasks.Task<ComercializadoraSoapProducts.RespuestaDTO> EliminarProductoAsync(int id)
        {
            return base.Channel.EliminarProductoAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProductoSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProductoSoapService))
            {
                return new System.ServiceModel.EndpointAddress("http://c9c5062dfe46.ngrok-free.app/WS/ProductoSoapService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProductoSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IProductoSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProductoSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IProductoSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IProductoSoapService,
        }
    }
}
