//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConUni_CliEsc_GR01.TemperaturaServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.monster.edu.ec/", ConfigurationName="ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService")]
    public interface TemperaturaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/TemperaturaService/CelsiusAFahrenheitRequest", ReplyAction="http://ws.monster.edu.ec/TemperaturaService/CelsiusAFahrenheitResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAFahrenheitResponse> CelsiusAFahrenheitAsync(ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAFahrenheitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/TemperaturaService/CelsiusAKelvinRequest", ReplyAction="http://ws.monster.edu.ec/TemperaturaService/CelsiusAKelvinResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAKelvinResponse> CelsiusAKelvinAsync(ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAKelvinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/TemperaturaService/FahrenheitACelsiusRequest", ReplyAction="http://ws.monster.edu.ec/TemperaturaService/FahrenheitACelsiusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitACelsiusResponse> FahrenheitACelsiusAsync(ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitACelsiusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/TemperaturaService/KelvinAFahrenheitRequest", ReplyAction="http://ws.monster.edu.ec/TemperaturaService/KelvinAFahrenheitResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinAFahrenheitResponse> KelvinAFahrenheitAsync(ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinAFahrenheitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/TemperaturaService/KelvinACelsiusRequest", ReplyAction="http://ws.monster.edu.ec/TemperaturaService/KelvinACelsiusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinACelsiusResponse> KelvinACelsiusAsync(ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinACelsiusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/TemperaturaService/FahrenheitAKelvinRequest", ReplyAction="http://ws.monster.edu.ec/TemperaturaService/FahrenheitAKelvinResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitAKelvinResponse> FahrenheitAKelvinAsync(ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitAKelvinRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class conversionResult
    {
        
        private bool exitosoField;
        
        private unidadConversion resultadoField;
        
        private conversionError errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool Exitoso
        {
            get
            {
                return this.exitosoField;
            }
            set
            {
                this.exitosoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public unidadConversion Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public conversionError Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class unidadConversion
    {
        
        private double valorOriginalField;
        
        private double valorConvertidoExactoField;
        
        private double valorConvertidoRedondeadoField;
        
        private string unidadOrigenField;
        
        private string unidadDestinoField;
        
        private double factorConversionField;
        
        private localDateTime fechaConversionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double valorOriginal
        {
            get
            {
                return this.valorOriginalField;
            }
            set
            {
                this.valorOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double valorConvertidoExacto
        {
            get
            {
                return this.valorConvertidoExactoField;
            }
            set
            {
                this.valorConvertidoExactoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double valorConvertidoRedondeado
        {
            get
            {
                return this.valorConvertidoRedondeadoField;
            }
            set
            {
                this.valorConvertidoRedondeadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string unidadOrigen
        {
            get
            {
                return this.unidadOrigenField;
            }
            set
            {
                this.unidadOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string unidadDestino
        {
            get
            {
                return this.unidadDestinoField;
            }
            set
            {
                this.unidadDestinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double factorConversion
        {
            get
            {
                return this.factorConversionField;
            }
            set
            {
                this.factorConversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public localDateTime fechaConversion
        {
            get
            {
                return this.fechaConversionField;
            }
            set
            {
                this.fechaConversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class localDateTime
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class conversionError
    {
        
        private string codigoErrorField;
        
        private string mensajeField;
        
        private string tipoErrorField;
        
        private double valorProblematicoField;
        
        private bool valorProblematicoFieldSpecified;
        
        private string unidadField;
        
        private localDateTime fechaErrorField;
        
        private string detallesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TipoError
        {
            get
            {
                return this.tipoErrorField;
            }
            set
            {
                this.tipoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double ValorProblematico
        {
            get
            {
                return this.valorProblematicoField;
            }
            set
            {
                this.valorProblematicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorProblematicoSpecified
        {
            get
            {
                return this.valorProblematicoFieldSpecified;
            }
            set
            {
                this.valorProblematicoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Unidad
        {
            get
            {
                return this.unidadField;
            }
            set
            {
                this.unidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public localDateTime FechaError
        {
            get
            {
                return this.fechaErrorField;
            }
            set
            {
                this.fechaErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Detalles
        {
            get
            {
                return this.detallesField;
            }
            set
            {
                this.detallesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CelsiusAFahrenheit", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class CelsiusAFahrenheitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string celsius;
        
        public CelsiusAFahrenheitRequest()
        {
        }
        
        public CelsiusAFahrenheitRequest(string celsius)
        {
            this.celsius = celsius;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CelsiusAFahrenheitResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class CelsiusAFahrenheitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConUni_CliEsc_GR01.TemperaturaServiceReference.conversionResult @return;
        
        public CelsiusAFahrenheitResponse()
        {
        }
        
        public CelsiusAFahrenheitResponse(ConUni_CliEsc_GR01.TemperaturaServiceReference.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CelsiusAKelvin", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class CelsiusAKelvinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string celsius;
        
        public CelsiusAKelvinRequest()
        {
        }
        
        public CelsiusAKelvinRequest(string celsius)
        {
            this.celsius = celsius;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CelsiusAKelvinResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class CelsiusAKelvinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConUni_CliEsc_GR01.TemperaturaServiceReference.conversionResult @return;
        
        public CelsiusAKelvinResponse()
        {
        }
        
        public CelsiusAKelvinResponse(ConUni_CliEsc_GR01.TemperaturaServiceReference.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FahrenheitACelsius", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class FahrenheitACelsiusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fahrenheit;
        
        public FahrenheitACelsiusRequest()
        {
        }
        
        public FahrenheitACelsiusRequest(string fahrenheit)
        {
            this.fahrenheit = fahrenheit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FahrenheitACelsiusResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class FahrenheitACelsiusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConUni_CliEsc_GR01.TemperaturaServiceReference.conversionResult @return;
        
        public FahrenheitACelsiusResponse()
        {
        }
        
        public FahrenheitACelsiusResponse(ConUni_CliEsc_GR01.TemperaturaServiceReference.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KelvinAFahrenheit", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class KelvinAFahrenheitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kelvin;
        
        public KelvinAFahrenheitRequest()
        {
        }
        
        public KelvinAFahrenheitRequest(string kelvin)
        {
            this.kelvin = kelvin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KelvinAFahrenheitResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class KelvinAFahrenheitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConUni_CliEsc_GR01.TemperaturaServiceReference.conversionResult @return;
        
        public KelvinAFahrenheitResponse()
        {
        }
        
        public KelvinAFahrenheitResponse(ConUni_CliEsc_GR01.TemperaturaServiceReference.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KelvinACelsius", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class KelvinACelsiusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kelvin;
        
        public KelvinACelsiusRequest()
        {
        }
        
        public KelvinACelsiusRequest(string kelvin)
        {
            this.kelvin = kelvin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KelvinACelsiusResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class KelvinACelsiusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConUni_CliEsc_GR01.TemperaturaServiceReference.conversionResult @return;
        
        public KelvinACelsiusResponse()
        {
        }
        
        public KelvinACelsiusResponse(ConUni_CliEsc_GR01.TemperaturaServiceReference.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FahrenheitAKelvin", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class FahrenheitAKelvinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fahrenheit;
        
        public FahrenheitAKelvinRequest()
        {
        }
        
        public FahrenheitAKelvinRequest(string fahrenheit)
        {
            this.fahrenheit = fahrenheit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FahrenheitAKelvinResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class FahrenheitAKelvinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConUni_CliEsc_GR01.TemperaturaServiceReference.conversionResult @return;
        
        public FahrenheitAKelvinResponse()
        {
        }
        
        public FahrenheitAKelvinResponse(ConUni_CliEsc_GR01.TemperaturaServiceReference.conversionResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface TemperaturaServiceChannel : ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TemperaturaServiceClient : System.ServiceModel.ClientBase<ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService>, ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TemperaturaServiceClient() : 
                base(TemperaturaServiceClient.GetDefaultBinding(), TemperaturaServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TemperaturaServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TemperaturaServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TemperaturaServiceClient.GetBindingForEndpoint(endpointConfiguration), TemperaturaServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TemperaturaServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TemperaturaServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TemperaturaServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TemperaturaServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TemperaturaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAFahrenheitResponse> ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService.CelsiusAFahrenheitAsync(ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAFahrenheitRequest request)
        {
            return base.Channel.CelsiusAFahrenheitAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAFahrenheitResponse> CelsiusAFahrenheitAsync(string celsius)
        {
            ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAFahrenheitRequest inValue = new ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAFahrenheitRequest();
            inValue.celsius = celsius;
            return ((ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService)(this)).CelsiusAFahrenheitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAKelvinResponse> ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService.CelsiusAKelvinAsync(ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAKelvinRequest request)
        {
            return base.Channel.CelsiusAKelvinAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAKelvinResponse> CelsiusAKelvinAsync(string celsius)
        {
            ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAKelvinRequest inValue = new ConUni_CliEsc_GR01.TemperaturaServiceReference.CelsiusAKelvinRequest();
            inValue.celsius = celsius;
            return ((ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService)(this)).CelsiusAKelvinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitACelsiusResponse> ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService.FahrenheitACelsiusAsync(ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitACelsiusRequest request)
        {
            return base.Channel.FahrenheitACelsiusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitACelsiusResponse> FahrenheitACelsiusAsync(string fahrenheit)
        {
            ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitACelsiusRequest inValue = new ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitACelsiusRequest();
            inValue.fahrenheit = fahrenheit;
            return ((ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService)(this)).FahrenheitACelsiusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinAFahrenheitResponse> ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService.KelvinAFahrenheitAsync(ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinAFahrenheitRequest request)
        {
            return base.Channel.KelvinAFahrenheitAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinAFahrenheitResponse> KelvinAFahrenheitAsync(string kelvin)
        {
            ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinAFahrenheitRequest inValue = new ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinAFahrenheitRequest();
            inValue.kelvin = kelvin;
            return ((ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService)(this)).KelvinAFahrenheitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinACelsiusResponse> ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService.KelvinACelsiusAsync(ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinACelsiusRequest request)
        {
            return base.Channel.KelvinACelsiusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinACelsiusResponse> KelvinACelsiusAsync(string kelvin)
        {
            ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinACelsiusRequest inValue = new ConUni_CliEsc_GR01.TemperaturaServiceReference.KelvinACelsiusRequest();
            inValue.kelvin = kelvin;
            return ((ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService)(this)).KelvinACelsiusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitAKelvinResponse> ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService.FahrenheitAKelvinAsync(ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitAKelvinRequest request)
        {
            return base.Channel.FahrenheitAKelvinAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitAKelvinResponse> FahrenheitAKelvinAsync(string fahrenheit)
        {
            ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitAKelvinRequest inValue = new ConUni_CliEsc_GR01.TemperaturaServiceReference.FahrenheitAKelvinRequest();
            inValue.fahrenheit = fahrenheit;
            return ((ConUni_CliEsc_GR01.TemperaturaServiceReference.TemperaturaService)(this)).FahrenheitAKelvinAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TemperaturaServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TemperaturaServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/ConUni_Soap_Java_GR01/TemperaturaService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TemperaturaServiceClient.GetBindingForEndpoint(EndpointConfiguration.TemperaturaServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TemperaturaServiceClient.GetEndpointAddress(EndpointConfiguration.TemperaturaServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            TemperaturaServicePort,
        }
    }
}
