//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercializadoraSoapBilling
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudCalculoDTO", Namespace="http://schemas.datacontract.org/2004/07/Comercializadora_Soap_DotNet_GR01.DTOs")]
    public partial class SolicitudCalculoDTO : object
    {
        
        private ComercializadoraSoapBilling.ItemFacturaDTO[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ComercializadoraSoapBilling.ItemFacturaDTO[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemFacturaDTO", Namespace="http://schemas.datacontract.org/2004/07/Comercializadora_Soap_DotNet_GR01.DTOs")]
    public partial class ItemFacturaDTO : object
    {
        
        private int CantidadField;
        
        private int ProductoIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductoId
        {
            get
            {
                return this.ProductoIdField;
            }
            set
            {
                this.ProductoIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalculoFacturaDTO", Namespace="http://schemas.datacontract.org/2004/07/Comercializadora_Soap_DotNet_GR01.DTOs")]
    public partial class CalculoFacturaDTO : object
    {
        
        private bool ExitosoField;
        
        private string MensajeField;
        
        private decimal TotalField;
        
        private ComercializadoraSoapBilling.DetalleCalculoDTO[] DetallesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso
        {
            get
            {
                return this.ExitosoField;
            }
            set
            {
                this.ExitosoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public ComercializadoraSoapBilling.DetalleCalculoDTO[] Detalles
        {
            get
            {
                return this.DetallesField;
            }
            set
            {
                this.DetallesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleCalculoDTO", Namespace="http://schemas.datacontract.org/2004/07/Comercializadora_Soap_DotNet_GR01.DTOs")]
    public partial class DetalleCalculoDTO : object
    {
        
        private int CantidadField;
        
        private string NombreProductoField;
        
        private decimal PrecioUnitarioField;
        
        private int ProductoIdField;
        
        private decimal SubtotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProducto
        {
            get
            {
                return this.NombreProductoField;
            }
            set
            {
                this.NombreProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario
        {
            get
            {
                return this.PrecioUnitarioField;
            }
            set
            {
                this.PrecioUnitarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductoId
        {
            get
            {
                return this.ProductoIdField;
            }
            set
            {
                this.ProductoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Subtotal
        {
            get
            {
                return this.SubtotalField;
            }
            set
            {
                this.SubtotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudFacturaDTO", Namespace="http://schemas.datacontract.org/2004/07/Comercializadora_Soap_DotNet_GR01.DTOs")]
    public partial class SolicitudFacturaDTO : object
    {
        
        private string CedulaClienteField;
        
        private string FormaPagoField;
        
        private ComercializadoraSoapBilling.ItemFacturaDTO[] ItemsField;
        
        private string NombreClienteField;
        
        private string NumeroCreditoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CedulaCliente
        {
            get
            {
                return this.CedulaClienteField;
            }
            set
            {
                this.CedulaClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaPago
        {
            get
            {
                return this.FormaPagoField;
            }
            set
            {
                this.FormaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ComercializadoraSoapBilling.ItemFacturaDTO[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCredito
        {
            get
            {
                return this.NumeroCreditoField;
            }
            set
            {
                this.NumeroCreditoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaDTO", Namespace="http://schemas.datacontract.org/2004/07/Comercializadora_Soap_DotNet_GR01.DTOs")]
    public partial class FacturaDTO : object
    {
        
        private string CedulaClienteField;
        
        private decimal DescuentoField;
        
        private ComercializadoraSoapBilling.DetalleFacturaDTO[] DetallesField;
        
        private int FacturaIdField;
        
        private System.DateTime FechaEmisionField;
        
        private string FormaPagoField;
        
        private string NombreClienteField;
        
        private string NumeroCreditoField;
        
        private string NumeroFacturaField;
        
        private decimal SubtotalField;
        
        private decimal TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CedulaCliente
        {
            get
            {
                return this.CedulaClienteField;
            }
            set
            {
                this.CedulaClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Descuento
        {
            get
            {
                return this.DescuentoField;
            }
            set
            {
                this.DescuentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ComercializadoraSoapBilling.DetalleFacturaDTO[] Detalles
        {
            get
            {
                return this.DetallesField;
            }
            set
            {
                this.DetallesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacturaId
        {
            get
            {
                return this.FacturaIdField;
            }
            set
            {
                this.FacturaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEmision
        {
            get
            {
                return this.FechaEmisionField;
            }
            set
            {
                this.FechaEmisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaPago
        {
            get
            {
                return this.FormaPagoField;
            }
            set
            {
                this.FormaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCredito
        {
            get
            {
                return this.NumeroCreditoField;
            }
            set
            {
                this.NumeroCreditoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura
        {
            get
            {
                return this.NumeroFacturaField;
            }
            set
            {
                this.NumeroFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Subtotal
        {
            get
            {
                return this.SubtotalField;
            }
            set
            {
                this.SubtotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleFacturaDTO", Namespace="http://schemas.datacontract.org/2004/07/Comercializadora_Soap_DotNet_GR01.DTOs")]
    public partial class DetalleFacturaDTO : object
    {
        
        private int CantidadField;
        
        private string NombreProductoField;
        
        private decimal PrecioUnitarioField;
        
        private int ProductoIdField;
        
        private decimal SubtotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProducto
        {
            get
            {
                return this.NombreProductoField;
            }
            set
            {
                this.NombreProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario
        {
            get
            {
                return this.PrecioUnitarioField;
            }
            set
            {
                this.PrecioUnitarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductoId
        {
            get
            {
                return this.ProductoIdField;
            }
            set
            {
                this.ProductoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Subtotal
        {
            get
            {
                return this.SubtotalField;
            }
            set
            {
                this.SubtotalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComercializadoraSoapBilling.IFacturacionSoapService")]
    public interface IFacturacionSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturacionSoapService/CalcularTotalFactura", ReplyAction="http://tempuri.org/IFacturacionSoapService/CalcularTotalFacturaResponse")]
        System.Threading.Tasks.Task<ComercializadoraSoapBilling.CalculoFacturaDTO> CalcularTotalFacturaAsync(ComercializadoraSoapBilling.SolicitudCalculoDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturacionSoapService/GenerarFactura", ReplyAction="http://tempuri.org/IFacturacionSoapService/GenerarFacturaResponse")]
        System.Threading.Tasks.Task<ComercializadoraSoapBilling.FacturaDTO> GenerarFacturaAsync(ComercializadoraSoapBilling.SolicitudFacturaDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturacionSoapService/ObtenerFacturasPorCliente", ReplyAction="http://tempuri.org/IFacturacionSoapService/ObtenerFacturasPorClienteResponse")]
        System.Threading.Tasks.Task<ComercializadoraSoapBilling.FacturaDTO[]> ObtenerFacturasPorClienteAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturacionSoapService/ObtenerFacturaPorNumero", ReplyAction="http://tempuri.org/IFacturacionSoapService/ObtenerFacturaPorNumeroResponse")]
        System.Threading.Tasks.Task<ComercializadoraSoapBilling.FacturaDTO> ObtenerFacturaPorNumeroAsync(string numeroFactura);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IFacturacionSoapServiceChannel : ComercializadoraSoapBilling.IFacturacionSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class FacturacionSoapServiceClient : System.ServiceModel.ClientBase<ComercializadoraSoapBilling.IFacturacionSoapService>, ComercializadoraSoapBilling.IFacturacionSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FacturacionSoapServiceClient() : 
                base(FacturacionSoapServiceClient.GetDefaultBinding(), FacturacionSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IFacturacionSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FacturacionSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(FacturacionSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), FacturacionSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FacturacionSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FacturacionSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FacturacionSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FacturacionSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FacturacionSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ComercializadoraSoapBilling.CalculoFacturaDTO> CalcularTotalFacturaAsync(ComercializadoraSoapBilling.SolicitudCalculoDTO solicitud)
        {
            return base.Channel.CalcularTotalFacturaAsync(solicitud);
        }
        
        public System.Threading.Tasks.Task<ComercializadoraSoapBilling.FacturaDTO> GenerarFacturaAsync(ComercializadoraSoapBilling.SolicitudFacturaDTO solicitud)
        {
            return base.Channel.GenerarFacturaAsync(solicitud);
        }
        
        public System.Threading.Tasks.Task<ComercializadoraSoapBilling.FacturaDTO[]> ObtenerFacturasPorClienteAsync(string cedula)
        {
            return base.Channel.ObtenerFacturasPorClienteAsync(cedula);
        }
        
        public System.Threading.Tasks.Task<ComercializadoraSoapBilling.FacturaDTO> ObtenerFacturaPorNumeroAsync(string numeroFactura)
        {
            return base.Channel.ObtenerFacturaPorNumeroAsync(numeroFactura);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFacturacionSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFacturacionSoapService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.40.11.26:8006/WS/FacturacionSoapService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FacturacionSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IFacturacionSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FacturacionSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IFacturacionSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IFacturacionSoapService,
        }
    }
}
