//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercializadora_Soap_DotNet_GR01.BanquitoSoap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidacionCreditoDTO", Namespace="http://schemas.datacontract.org/2004/07/BanquitoServer_Soap_DotNet_GR01.DTOs")]
    [System.SerializableAttribute()]
    public partial class ValidacionCreditoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsValidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsValido {
            get {
                return this.EsValidoField;
            }
            set {
                if ((this.EsValidoField.Equals(value) != true)) {
                    this.EsValidoField = value;
                    this.RaisePropertyChanged("EsValido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MontoMaximoCreditoDTO", Namespace="http://schemas.datacontract.org/2004/07/BanquitoServer_Soap_DotNet_GR01.DTOs")]
    [System.SerializableAttribute()]
    public partial class MontoMaximoCreditoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoMaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PromedioDepositosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PromedioRetirosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoMaximo {
            get {
                return this.MontoMaximoField;
            }
            set {
                if ((this.MontoMaximoField.Equals(value) != true)) {
                    this.MontoMaximoField = value;
                    this.RaisePropertyChanged("MontoMaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PromedioDepositos {
            get {
                return this.PromedioDepositosField;
            }
            set {
                if ((this.PromedioDepositosField.Equals(value) != true)) {
                    this.PromedioDepositosField = value;
                    this.RaisePropertyChanged("PromedioDepositos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PromedioRetiros {
            get {
                return this.PromedioRetirosField;
            }
            set {
                if ((this.PromedioRetirosField.Equals(value) != true)) {
                    this.PromedioRetirosField = value;
                    this.RaisePropertyChanged("PromedioRetiros");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudCreditoDTO", Namespace="http://schemas.datacontract.org/2004/07/BanquitoServer_Soap_DotNet_GR01.DTOs")]
    [System.SerializableAttribute()]
    public partial class SolicitudCreditoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroCuotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioElectrodomesticoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCuotas {
            get {
                return this.NumeroCuotasField;
            }
            set {
                if ((this.NumeroCuotasField.Equals(value) != true)) {
                    this.NumeroCuotasField = value;
                    this.RaisePropertyChanged("NumeroCuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioElectrodomestico {
            get {
                return this.PrecioElectrodomesticoField;
            }
            set {
                if ((this.PrecioElectrodomesticoField.Equals(value) != true)) {
                    this.PrecioElectrodomesticoField = value;
                    this.RaisePropertyChanged("PrecioElectrodomestico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCreditoDTO", Namespace="http://schemas.datacontract.org/2004/07/BanquitoServer_Soap_DotNet_GR01.DTOs")]
    [System.SerializableAttribute()]
    public partial class RespuestaCreditoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CuotaMensualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroCuotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comercializadora_Soap_DotNet_GR01.BanquitoSoap.CuotaAmortizacionDTO[] TablaAmortizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TasaInteresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CuotaMensual {
            get {
                return this.CuotaMensualField;
            }
            set {
                if ((this.CuotaMensualField.Equals(value) != true)) {
                    this.CuotaMensualField = value;
                    this.RaisePropertyChanged("CuotaMensual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoCredito {
            get {
                return this.MontoCreditoField;
            }
            set {
                if ((this.MontoCreditoField.Equals(value) != true)) {
                    this.MontoCreditoField = value;
                    this.RaisePropertyChanged("MontoCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCredito {
            get {
                return this.NumeroCreditoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCreditoField, value) != true)) {
                    this.NumeroCreditoField = value;
                    this.RaisePropertyChanged("NumeroCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCuotas {
            get {
                return this.NumeroCuotasField;
            }
            set {
                if ((this.NumeroCuotasField.Equals(value) != true)) {
                    this.NumeroCuotasField = value;
                    this.RaisePropertyChanged("NumeroCuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Comercializadora_Soap_DotNet_GR01.BanquitoSoap.CuotaAmortizacionDTO[] TablaAmortizacion {
            get {
                return this.TablaAmortizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TablaAmortizacionField, value) != true)) {
                    this.TablaAmortizacionField = value;
                    this.RaisePropertyChanged("TablaAmortizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TasaInteres {
            get {
                return this.TasaInteresField;
            }
            set {
                if ((this.TasaInteresField.Equals(value) != true)) {
                    this.TasaInteresField = value;
                    this.RaisePropertyChanged("TasaInteres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuotaAmortizacionDTO", Namespace="http://schemas.datacontract.org/2004/07/BanquitoServer_Soap_DotNet_GR01.DTOs")]
    [System.SerializableAttribute()]
    public partial class CuotaAmortizacionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CapitalPagadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InteresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCuotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CapitalPagado {
            get {
                return this.CapitalPagadoField;
            }
            set {
                if ((this.CapitalPagadoField.Equals(value) != true)) {
                    this.CapitalPagadoField = value;
                    this.RaisePropertyChanged("CapitalPagado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Interes {
            get {
                return this.InteresField;
            }
            set {
                if ((this.InteresField.Equals(value) != true)) {
                    this.InteresField = value;
                    this.RaisePropertyChanged("Interes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCuota {
            get {
                return this.NumeroCuotaField;
            }
            set {
                if ((this.NumeroCuotaField.Equals(value) != true)) {
                    this.NumeroCuotaField = value;
                    this.RaisePropertyChanged("NumeroCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCuota {
            get {
                return this.ValorCuotaField;
            }
            set {
                if ((this.ValorCuotaField.Equals(value) != true)) {
                    this.ValorCuotaField = value;
                    this.RaisePropertyChanged("ValorCuota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BanquitoSoap.ICreditoSoapService")]
    public interface ICreditoSoapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoSoapService/ValidarSujetoCredito", ReplyAction="http://tempuri.org/ICreditoSoapService/ValidarSujetoCreditoResponse")]
        Comercializadora_Soap_DotNet_GR01.BanquitoSoap.ValidacionCreditoDTO ValidarSujetoCredito(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoSoapService/ValidarSujetoCredito", ReplyAction="http://tempuri.org/ICreditoSoapService/ValidarSujetoCreditoResponse")]
        System.Threading.Tasks.Task<Comercializadora_Soap_DotNet_GR01.BanquitoSoap.ValidacionCreditoDTO> ValidarSujetoCreditoAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoSoapService/ObtenerMontoMaximo", ReplyAction="http://tempuri.org/ICreditoSoapService/ObtenerMontoMaximoResponse")]
        Comercializadora_Soap_DotNet_GR01.BanquitoSoap.MontoMaximoCreditoDTO ObtenerMontoMaximo(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoSoapService/ObtenerMontoMaximo", ReplyAction="http://tempuri.org/ICreditoSoapService/ObtenerMontoMaximoResponse")]
        System.Threading.Tasks.Task<Comercializadora_Soap_DotNet_GR01.BanquitoSoap.MontoMaximoCreditoDTO> ObtenerMontoMaximoAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoSoapService/OtorgarCredito", ReplyAction="http://tempuri.org/ICreditoSoapService/OtorgarCreditoResponse")]
        Comercializadora_Soap_DotNet_GR01.BanquitoSoap.RespuestaCreditoDTO OtorgarCredito(Comercializadora_Soap_DotNet_GR01.BanquitoSoap.SolicitudCreditoDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoSoapService/OtorgarCredito", ReplyAction="http://tempuri.org/ICreditoSoapService/OtorgarCreditoResponse")]
        System.Threading.Tasks.Task<Comercializadora_Soap_DotNet_GR01.BanquitoSoap.RespuestaCreditoDTO> OtorgarCreditoAsync(Comercializadora_Soap_DotNet_GR01.BanquitoSoap.SolicitudCreditoDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoSoapService/ObtenerTablaAmortizacion", ReplyAction="http://tempuri.org/ICreditoSoapService/ObtenerTablaAmortizacionResponse")]
        Comercializadora_Soap_DotNet_GR01.BanquitoSoap.CuotaAmortizacionDTO[] ObtenerTablaAmortizacion(string numeroCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoSoapService/ObtenerTablaAmortizacion", ReplyAction="http://tempuri.org/ICreditoSoapService/ObtenerTablaAmortizacionResponse")]
        System.Threading.Tasks.Task<Comercializadora_Soap_DotNet_GR01.BanquitoSoap.CuotaAmortizacionDTO[]> ObtenerTablaAmortizacionAsync(string numeroCredito);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditoSoapServiceChannel : Comercializadora_Soap_DotNet_GR01.BanquitoSoap.ICreditoSoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditoSoapServiceClient : System.ServiceModel.ClientBase<Comercializadora_Soap_DotNet_GR01.BanquitoSoap.ICreditoSoapService>, Comercializadora_Soap_DotNet_GR01.BanquitoSoap.ICreditoSoapService {
        
        public CreditoSoapServiceClient() {
        }
        
        public CreditoSoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditoSoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditoSoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditoSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Comercializadora_Soap_DotNet_GR01.BanquitoSoap.ValidacionCreditoDTO ValidarSujetoCredito(string cedula) {
            return base.Channel.ValidarSujetoCredito(cedula);
        }
        
        public System.Threading.Tasks.Task<Comercializadora_Soap_DotNet_GR01.BanquitoSoap.ValidacionCreditoDTO> ValidarSujetoCreditoAsync(string cedula) {
            return base.Channel.ValidarSujetoCreditoAsync(cedula);
        }
        
        public Comercializadora_Soap_DotNet_GR01.BanquitoSoap.MontoMaximoCreditoDTO ObtenerMontoMaximo(string cedula) {
            return base.Channel.ObtenerMontoMaximo(cedula);
        }
        
        public System.Threading.Tasks.Task<Comercializadora_Soap_DotNet_GR01.BanquitoSoap.MontoMaximoCreditoDTO> ObtenerMontoMaximoAsync(string cedula) {
            return base.Channel.ObtenerMontoMaximoAsync(cedula);
        }
        
        public Comercializadora_Soap_DotNet_GR01.BanquitoSoap.RespuestaCreditoDTO OtorgarCredito(Comercializadora_Soap_DotNet_GR01.BanquitoSoap.SolicitudCreditoDTO solicitud) {
            return base.Channel.OtorgarCredito(solicitud);
        }
        
        public System.Threading.Tasks.Task<Comercializadora_Soap_DotNet_GR01.BanquitoSoap.RespuestaCreditoDTO> OtorgarCreditoAsync(Comercializadora_Soap_DotNet_GR01.BanquitoSoap.SolicitudCreditoDTO solicitud) {
            return base.Channel.OtorgarCreditoAsync(solicitud);
        }
        
        public Comercializadora_Soap_DotNet_GR01.BanquitoSoap.CuotaAmortizacionDTO[] ObtenerTablaAmortizacion(string numeroCredito) {
            return base.Channel.ObtenerTablaAmortizacion(numeroCredito);
        }
        
        public System.Threading.Tasks.Task<Comercializadora_Soap_DotNet_GR01.BanquitoSoap.CuotaAmortizacionDTO[]> ObtenerTablaAmortizacionAsync(string numeroCredito) {
            return base.Channel.ObtenerTablaAmortizacionAsync(numeroCredito);
        }
    }
}
