//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanQuitoSoapCredit
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidacionCreditoDTO", Namespace="http://schemas.datacontract.org/2004/07/BanquitoServer_Soap_DotNet_GR01.DTOs")]
    public partial class ValidacionCreditoDTO : object
    {
        
        private string CedulaField;
        
        private bool EsValidoField;
        
        private string MensajeField;
        
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula
        {
            get
            {
                return this.CedulaField;
            }
            set
            {
                this.CedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsValido
        {
            get
            {
                return this.EsValidoField;
            }
            set
            {
                this.EsValidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto
        {
            get
            {
                return this.NombreCompletoField;
            }
            set
            {
                this.NombreCompletoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MontoMaximoCreditoDTO", Namespace="http://schemas.datacontract.org/2004/07/BanquitoServer_Soap_DotNet_GR01.DTOs")]
    public partial class MontoMaximoCreditoDTO : object
    {
        
        private string CedulaField;
        
        private string MensajeField;
        
        private decimal MontoMaximoField;
        
        private decimal PromedioDepositosField;
        
        private decimal PromedioRetirosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula
        {
            get
            {
                return this.CedulaField;
            }
            set
            {
                this.CedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoMaximo
        {
            get
            {
                return this.MontoMaximoField;
            }
            set
            {
                this.MontoMaximoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PromedioDepositos
        {
            get
            {
                return this.PromedioDepositosField;
            }
            set
            {
                this.PromedioDepositosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PromedioRetiros
        {
            get
            {
                return this.PromedioRetirosField;
            }
            set
            {
                this.PromedioRetirosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudCreditoDTO", Namespace="http://schemas.datacontract.org/2004/07/BanquitoServer_Soap_DotNet_GR01.DTOs")]
    public partial class SolicitudCreditoDTO : object
    {
        
        private string CedulaField;
        
        private string NumeroCuotasField;
        
        private string PrecioElectrodomesticoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula
        {
            get
            {
                return this.CedulaField;
            }
            set
            {
                this.CedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCuotas
        {
            get
            {
                return this.NumeroCuotasField;
            }
            set
            {
                this.NumeroCuotasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrecioElectrodomestico
        {
            get
            {
                return this.PrecioElectrodomesticoField;
            }
            set
            {
                this.PrecioElectrodomesticoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCreditoDTO", Namespace="http://schemas.datacontract.org/2004/07/BanquitoServer_Soap_DotNet_GR01.DTOs")]
    public partial class RespuestaCreditoDTO : object
    {
        
        private string CedulaField;
        
        private decimal CuotaMensualField;
        
        private bool ExitoField;
        
        private string MensajeField;
        
        private decimal MontoCreditoField;
        
        private string NumeroCreditoField;
        
        private int NumeroCuotasField;
        
        private BanQuitoSoapCredit.CuotaAmortizacionDTO[] TablaAmortizacionField;
        
        private decimal TasaInteresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula
        {
            get
            {
                return this.CedulaField;
            }
            set
            {
                this.CedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CuotaMensual
        {
            get
            {
                return this.CuotaMensualField;
            }
            set
            {
                this.CuotaMensualField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito
        {
            get
            {
                return this.ExitoField;
            }
            set
            {
                this.ExitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoCredito
        {
            get
            {
                return this.MontoCreditoField;
            }
            set
            {
                this.MontoCreditoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCredito
        {
            get
            {
                return this.NumeroCreditoField;
            }
            set
            {
                this.NumeroCreditoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCuotas
        {
            get
            {
                return this.NumeroCuotasField;
            }
            set
            {
                this.NumeroCuotasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanQuitoSoapCredit.CuotaAmortizacionDTO[] TablaAmortizacion
        {
            get
            {
                return this.TablaAmortizacionField;
            }
            set
            {
                this.TablaAmortizacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TasaInteres
        {
            get
            {
                return this.TasaInteresField;
            }
            set
            {
                this.TasaInteresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuotaAmortizacionDTO", Namespace="http://schemas.datacontract.org/2004/07/BanquitoServer_Soap_DotNet_GR01.DTOs")]
    public partial class CuotaAmortizacionDTO : object
    {
        
        private decimal CapitalPagadoField;
        
        private decimal InteresField;
        
        private int NumeroCuotaField;
        
        private decimal SaldoField;
        
        private decimal ValorCuotaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CapitalPagado
        {
            get
            {
                return this.CapitalPagadoField;
            }
            set
            {
                this.CapitalPagadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Interes
        {
            get
            {
                return this.InteresField;
            }
            set
            {
                this.InteresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCuota
        {
            get
            {
                return this.NumeroCuotaField;
            }
            set
            {
                this.NumeroCuotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saldo
        {
            get
            {
                return this.SaldoField;
            }
            set
            {
                this.SaldoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCuota
        {
            get
            {
                return this.ValorCuotaField;
            }
            set
            {
                this.ValorCuotaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BanQuitoSoapCredit.ICreditoSoapService")]
    public interface ICreditoSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoSoapService/ValidarSujetoCredito", ReplyAction="http://tempuri.org/ICreditoSoapService/ValidarSujetoCreditoResponse")]
        System.Threading.Tasks.Task<BanQuitoSoapCredit.ValidacionCreditoDTO> ValidarSujetoCreditoAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoSoapService/ObtenerMontoMaximo", ReplyAction="http://tempuri.org/ICreditoSoapService/ObtenerMontoMaximoResponse")]
        System.Threading.Tasks.Task<BanQuitoSoapCredit.MontoMaximoCreditoDTO> ObtenerMontoMaximoAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoSoapService/OtorgarCredito", ReplyAction="http://tempuri.org/ICreditoSoapService/OtorgarCreditoResponse")]
        System.Threading.Tasks.Task<BanQuitoSoapCredit.RespuestaCreditoDTO> OtorgarCreditoAsync(BanQuitoSoapCredit.SolicitudCreditoDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoSoapService/ObtenerTablaAmortizacion", ReplyAction="http://tempuri.org/ICreditoSoapService/ObtenerTablaAmortizacionResponse")]
        System.Threading.Tasks.Task<BanQuitoSoapCredit.CuotaAmortizacionDTO[]> ObtenerTablaAmortizacionAsync(string numeroCredito);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ICreditoSoapServiceChannel : BanQuitoSoapCredit.ICreditoSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CreditoSoapServiceClient : System.ServiceModel.ClientBase<BanQuitoSoapCredit.ICreditoSoapService>, BanQuitoSoapCredit.ICreditoSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CreditoSoapServiceClient() : 
                base(CreditoSoapServiceClient.GetDefaultBinding(), CreditoSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICreditoSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditoSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CreditoSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), CreditoSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditoSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CreditoSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditoSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CreditoSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditoSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<BanQuitoSoapCredit.ValidacionCreditoDTO> ValidarSujetoCreditoAsync(string cedula)
        {
            return base.Channel.ValidarSujetoCreditoAsync(cedula);
        }
        
        public System.Threading.Tasks.Task<BanQuitoSoapCredit.MontoMaximoCreditoDTO> ObtenerMontoMaximoAsync(string cedula)
        {
            return base.Channel.ObtenerMontoMaximoAsync(cedula);
        }
        
        public System.Threading.Tasks.Task<BanQuitoSoapCredit.RespuestaCreditoDTO> OtorgarCreditoAsync(BanQuitoSoapCredit.SolicitudCreditoDTO solicitud)
        {
            return base.Channel.OtorgarCreditoAsync(solicitud);
        }
        
        public System.Threading.Tasks.Task<BanQuitoSoapCredit.CuotaAmortizacionDTO[]> ObtenerTablaAmortizacionAsync(string numeroCredito)
        {
            return base.Channel.ObtenerTablaAmortizacionAsync(numeroCredito);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICreditoSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICreditoSoapService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.40.11.26:8007/WS/CreditoSoapService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CreditoSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICreditoSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CreditoSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICreditoSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICreditoSoapService,
        }
    }
}
